// Buyer-intent articles: written for people actively comparing and ready to
// enquire. Facts only — pricing comes from the confirmed membership tiers,
// private sessions stay enquiry-based, and no health outcome is promised.
import type { BlogPost } from "@/lib/blog/types";

export const BUYER_POSTS: BlogPost[] = [
  {
    slug: "how-much-do-online-yoga-classes-cost",
    cat: "Pricing",
    cluster: "online",
    primaryKeyword: "online yoga classes cost",
    title: "How much do live online yoga classes cost? A clear price breakdown",
    seoTitle: "How Much Do Live Online Yoga Classes Cost? (2026 Prices)",
    excerpt:
      "What live online yoga actually costs, how membership lengths compare per month, why private 1-on-1 sessions are quoted separately, and what is included.",
    metaDescription:
      "Live online yoga membership prices from $36 per month, with per-month costs for 3, 6 and 12-month plans, what is included, and how private 1-on-1 pricing works.",
    read: "6 min",
    date: "2026-09-26",
    keyTakeaways: [
      "Yog Jivan live online memberships are $36 for one month, dropping to about $25 a month on the 12-month plan.",
      "Every membership includes live 60-minute classes with a maximum of eight students and real-time correction.",
      "Private 1-on-1 online sessions are quoted by enquiry, because they depend on frequency and format.",
    ],
    body: [
      { type: "p", text: "Most people comparing online yoga are really comparing two different products: a video library you watch alone, and a live class where a teacher can see you and correct you. The prices below are for live classes with a real teacher on screen, which is the only format Yog Jivan teaches online." },
      { type: "h2", text: "Live online membership prices" },
      { type: "ul", items: [
        "1 month — $36",
        "3 months — $99 (about $33 per month)",
        "6 months — $180 (about $30 per month)",
        "12 months — $300 (about $25 per month)",
      ]},
      { type: "p", text: "Prices are in USD. Longer memberships cost less per month because they reflect a commitment to a regular weekly rhythm, which is also what makes practice work." },
      { type: "h2", text: "What the price includes" },
      { type: "ul", items: [
        "Live 60-minute classes on Zoom, never pre-recorded.",
        "A maximum of eight students per class, so the teacher can see and correct each person.",
        "Teaching in English, Vietnamese and Hindi.",
        "A catch-up recording available to members for 48 hours if you miss a class.",
        "A short 15-minute onboarding and practice-safety conversation before your first class.",
      ]},
      { type: "h2", text: "Why private 1-on-1 sessions are priced separately" },
      { type: "p", text: "A private session is a whole hour built around one person: your level, your limitations, your schedule and your goals. Because the right number of sessions per week and the format differ from student to student, private pricing is confirmed by enquiry rather than published as a fixed package. There is no payment requested when you enquire." },
      { type: "h2", text: "Is live online yoga worth it compared with free videos?" },
      { type: "p", text: "Free videos are excellent for following along when you already know the postures. What they cannot do is tell you that your knee is tracking inward, that your lower back is compensating, or that a posture should be modified for you today. A live class is the paid part of that difference. If you practise mainly for relaxation and already move well, free video may be enough; if you want your alignment watched and adjusted, a live class is the reason to pay." },
      { type: "h2", text: "How to work out your real cost" },
      { type: "p", text: "Divide the membership price by the number of classes you will realistically attend in that period. A 12-month membership attended twice a week works out to a very low cost per live, corrected hour. A one-month membership attended twice in total does not. Choose the length that matches the rhythm you can actually keep." },
    ],
    related: [
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      { label: "Programs & Pricing", to: "/programs" },
      { label: "Live online yoga vs YouTube", to: "/blog/live-online-yoga-vs-youtube" },
    ],
    faqs: [
      { q: "How much does a live online yoga class cost?", a: "Yog Jivan live online memberships are $36 for one month. The 12-month plan works out to about $25 per month. All plans include live 60-minute classes capped at eight students." },
      { q: "Do you charge for a trial class?", a: "New students start with our introductory offer for the live online group classes. Message us and we will arrange it." },
      { q: "How much is a private 1-on-1 online yoga session?", a: "Private sessions are quoted by enquiry, because pricing depends on frequency and format. No payment is requested when you enquire." },
      { q: "Are there refunds?", a: "Memberships are generally non-refundable once activated or after the first class is used, with exceptions for duplicate payment, cancellation by Yog Jivan, service failure and your rights under applicable consumer law." },
    ],
    cta: {
      title: "Not sure which plan fits?",
      sub: "Tell us how often you can realistically practise and we will suggest the sensible option — not the most expensive one.",
      primary: { label: "See live online classes", to: "/online-yoga-classes" },
      secondary: { label: "Ask about private 1-on-1", to: "/private-online-yoga" },
    },
  },
  {
    slug: "online-yoga-with-posture-correction",
    cat: "Comparison",
    cluster: "comparison",
    primaryKeyword: "online yoga with posture correction",
    title: "Online yoga with real posture correction: what it is and how to check you are getting it",
    seoTitle: "Online Yoga With Real Posture Correction — How to Check",
    excerpt:
      "How a teacher actually corrects your alignment over video, what the camera setup needs to be, and the questions to ask before paying for any online class.",
    metaDescription:
      "How live online yoga teachers correct posture over video, what camera angle and group size make it possible, and the questions to ask before paying.",
    read: "7 min",
    date: "2026-09-26",
    keyTakeaways: [
      "Correction over video is only possible when the class is live, the group is small and your whole body is visible.",
      "Ask for the maximum group size before paying — large live classes cannot deliver individual correction.",
      "Yog Jivan caps live online groups at eight students and requires camera on for exactly this reason.",
    ],
    body: [
      { type: "p", text: "Almost every online yoga service now describes itself as personal. Very few can actually tell you what your body is doing. This article explains the mechanics of correction over video, so you can judge any class — ours included — before you pay for it." },
      { type: "h2", text: "What correction over video actually requires" },
      { type: "ul", items: [
        "A live class. A recording cannot see you at all.",
        "A small group. A teacher watching forty tiles is watching nobody.",
        "Camera on, with your whole mat in frame from the side.",
        "A teacher who uses your name and gives specific cues, not general ones.",
      ]},
      { type: "p", text: "When those four things are in place, a teacher can see most of what matters: the line of your spine, whether your weight sits evenly, whether a knee collapses inward, whether your shoulders climb in a posture. What a teacher cannot do over video is place a hand on you, so the correction arrives as a precise verbal cue and a demonstrated modification instead." },
      { type: "h2", text: "How to set your camera so you can be corrected" },
      { type: "ul", items: [
        "Place the device at the side of your mat, not in front of your head.",
        "Raise it to roughly hip or knee height so the whole mat fits.",
        "Stand back until your fingertips and feet stay in frame in a standing posture.",
        "Light your front, not your back — a bright window behind you turns you into a silhouette.",
      ]},
      { type: "h2", text: "Questions worth asking before you pay" },
      { type: "ul", items: [
        "What is the maximum number of students in a live class?",
        "Is the class live, or a recording played at a set time?",
        "Is my camera required to be on?",
        "Will the same teacher take my classes each week?",
        "Can the teacher modify a posture for me during the class?",
      ]},
      { type: "p", text: "For reference: Yog Jivan live online group classes run 60 minutes on Zoom, are capped at eight students, require camera on, and are taught in English, Vietnamese and Hindi. Private 1-on-1 online sessions go further — the full hour is yours, and the pace and posture selection are built around you." },
      { type: "h2", text: "Group correction or private correction?" },
      { type: "p", text: "In a capped group you are seen and corrected several times in a class, inside a sequence designed for the group. In a private session every cue in the hour is yours, and the sequence itself is chosen for your body and schedule. If you have a specific limitation or a difficult schedule, private is the more efficient route. If you want routine and company at a lower cost, a small live group is usually enough." },
    ],
    related: [
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      { label: "Camera setup for online yoga", to: "/blog/online-yoga-camera-setup" },
      { label: "Can an online teacher correct your posture?", to: "/blog/can-an-online-yoga-teacher-correct-your-posture" },
    ],
    faqs: [
      { q: "Can a teacher really correct posture over video?", a: "Yes, when the class is live, the group is small and your whole body is in frame. The teacher sees your alignment and gives a specific verbal cue or a modification. Hands-on adjustment is the one thing video cannot provide." },
      { q: "How many students should a live online class have?", a: "Small enough that the teacher can watch each person. Yog Jivan caps live online groups at eight students." },
      { q: "Do I have to keep my camera on?", a: "Yes, in Yog Jivan live online classes. Without it the teacher cannot see your alignment and correction is not possible." },
    ],
    cta: {
      title: "See whether you are being corrected",
      sub: "Join a live class with your camera on and judge the difference for yourself.",
      primary: { label: "See live online classes", to: "/online-yoga-classes" },
      secondary: { label: "Enquire about private 1-on-1", to: "/private-online-yoga" },
    },
  },
  {
    slug: "online-yoga-for-desk-stiffness-and-back-tension",
    cat: "Online",
    cluster: "deskwork",
    primaryKeyword: "online yoga for back and neck stiffness",
    title: "Online yoga for desk stiffness: choosing a class when your back and neck ache from sitting",
    seoTitle: "Online Yoga for Desk Stiffness, Back and Neck Tension",
    excerpt:
      "What to look for in an online class when long hours at a desk leave your back, neck and shoulders stiff — and when a private session is the better choice.",
    metaDescription:
      "How to choose an online yoga class for desk-related back, neck and shoulder stiffness: class format, correction, timing, and when private 1-on-1 suits better.",
    read: "7 min",
    date: "2026-09-26",
    keyTakeaways: [
      "Desk stiffness responds to short, frequent, well-guided practice more than to occasional long sessions.",
      "Correction matters here: unsupervised stretching often reinforces the same posture that caused the stiffness.",
      "Yoga supports general wellbeing and complements, but never replaces, medical care for pain.",
    ],
    body: [
      { type: "p", text: "If you sit for most of the working day, the stiffness you feel in the evening is usually the accumulated result of one position held for hours. A yoga class can help you move well again — but only if it is guided, regular and matched to what your body currently does. This article is about choosing that class, not about treating a diagnosis." },
      { type: "h2", text: "Why unsupervised stretching often disappoints" },
      { type: "p", text: "Most people who stretch alone repeat the shapes they can already do and avoid the ones they cannot. Over time this reinforces the imbalance instead of easing it. In a live class, the teacher notices the compensation — the shoulder that lifts, the lower back that takes over, the breath that stops — and gives a cue you cannot see for yourself." },
      { type: "h2", text: "What to look for in a class for desk stiffness" },
      { type: "ul", items: [
        "A live teacher who can see you, not a recording.",
        "A small group, so corrections actually reach you.",
        "A class time you can keep on a working day — early morning or evening.",
        "Breathwork included, because desk tension and shallow breathing travel together.",
        "A teacher who asks about your limitations before the first class.",
      ]},
      { type: "h2", text: "Group class or private session?" },
      { type: "p", text: "A small live group works well if your stiffness is general and your schedule is stable. A private 1-on-1 session is the better fit when you have a specific limitation, a past injury you need worked around, or working hours that never repeat. In a private hour the sequence itself is chosen around your body and can be changed week to week as things ease." },
      { type: "h2", text: "A realistic picture of progress" },
      { type: "p", text: "Change is gradual and personal. Some people notice easier movement within a few weeks of regular practice; others take longer, and progress is rarely a straight line. What consistently matters more than intensity is frequency and correct guidance. Practise moderately and often rather than hard and rarely." },
      { type: "h2", text: "An important limit" },
      { type: "p", text: "Yoga is not medical treatment. If you have persistent or severe pain, numbness, tingling, or pain following an injury or surgery, see a qualified medical professional first and practise with their clearance. Yoga supports general wellbeing and complements medical care; it does not replace it, and we do not promise specific medical outcomes." },
      { type: "h2", text: "How to start" },
      { type: "p", text: "Tell us your working hours, how long you sit, and anything a teacher should know before you move. We will suggest either a live group class or a private session — whichever genuinely fits, not whichever costs more." },
    ],
    related: [
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      { label: "Yoga for Back Pain", to: "/yoga-for-back-pain" },
      { label: "Desk worker yoga for back, neck and shoulders", to: "/blog/desk-worker-yoga-back-neck-shoulders" },
    ],
    faqs: [
      { q: "Can online yoga help with stiffness from sitting all day?", a: "Regular, well-guided yoga can support easier movement and general wellbeing for people who sit for long hours. It is not medical treatment, and persistent or severe pain should be assessed by a medical professional first." },
      { q: "How often should I practise?", a: "Frequency matters more than intensity. Two or three guided sessions a week, kept up consistently, generally serves desk-related stiffness better than one long session." },
      { q: "Should I choose a group class or a private session?", a: "A small live group suits general stiffness and a stable schedule. A private 1-on-1 session suits specific limitations, past injuries or irregular working hours, because the sequence is built around you." },
    ],
    cta: {
      title: "Tell us how your week actually looks",
      sub: "We will suggest a class time and format that fits your working hours, not an idealised schedule.",
      primary: { label: "See live online classes", to: "/online-yoga-classes" },
      secondary: { label: "Enquire about private 1-on-1", to: "/private-online-yoga" },
    },
  },
];
