// High-intent articles supporting the local, online, comparison and desk-work clusters.
import type { BlogPost } from "@/lib/blog/types";

export const GROWTH_POSTS: BlogPost[] = [
  {
    slug: "yoga-classes-hai-duong-beginners-guide",
    cat: "Local",
    cluster: "local",
    primaryKeyword: "yoga classes hai duong",
    title: "Yoga classes in Hai Duong: a beginner's guide to choosing your first class",
    seoTitle: "Yoga Classes in Hai Duong: Beginner's Guide",
    excerpt:
      "How to choose between group and private yoga in the Hai Duong urban area, what to expect in your first class, what to bring and how to enquire.",
    metaDescription:
      "A practical guide to starting yoga in the Hai Duong urban area: group vs private classes, what to bring, what happens in a first class, and how to book.",
    read: "8 min",
    date: "2026-08-06",
    keyTakeaways: [
      "Yog Jivan runs two studios serving the Hai Duong urban area, plus live online classes.",
      "Aerial yoga is available at Studio 1 only.",
      "Group classes suit most beginners; private 60-minute sessions suit specific needs and schedules.",
    ],
    body: [
      { type: "p", text: "If you are looking for yoga classes in the Hai Duong urban area and you have never practised before, the main decision is simple: a group class or a private session. This guide explains the difference, what a first class is actually like, what to bring, and how to arrange it with Yog Jivan." },
      { type: "h2", text: "Where Yog Jivan teaches" },
      { type: "p", text: "Yog Jivan runs two studios serving the Hai Duong urban area of Hai Phong. Studio 1 is Yog Jivan Sanctuary on Bùi Thị Xuân in Phường Lê Thanh Nghị, and it is the studio where aerial yoga is available. Studio 2 is Yog Jivan Yoga Studio at Nhà Văn Hóa Lao Động, Ngô Quyền in Phường Thành Đông; aerial yoga is not offered there. Classes at both studios are taught by the Yog Jivan teaching team, founded and led by Master Anil Choudhary, Founder & Lead Yoga Teacher." },
      { type: "h2", text: "Group classes or private sessions?" },
      { type: "ul", items: [
        "Group classes: a shared, structured session with other students. Good for routine, motivation and cost, and suitable for most beginners.",
        "Private sessions: live 60-minute one-to-one work, in studio or online, with the pace and content built around you. Useful if you have a specific limitation, a difficult schedule, or would prefer not to start in a group.",
        "Aerial yoga: available at Studio 1 only, and best approached after some general practice.",
        "Live online classes: 60 minutes, maximum eight students, taught in English, Vietnamese and Hindi — useful if you travel or work irregular hours.",
      ]},
      { type: "p", text: "Studio membership options are listed on our programs and pricing page. Private session scheduling and pricing are confirmed by enquiry rather than published, because they depend on frequency and format." },
      { type: "h2", text: "What actually happens in a first class" },
      { type: "p", text: "You will be asked briefly about any injuries, health conditions or recent surgery before you start. The session then begins with simple warming movement, moves into basic standing and seated postures, and ends with a short breathing practice and rest. You will not be expected to keep up with experienced students, and you will not be asked to do anything that feels unsafe. Master Anil gives verbal corrections during the class, so you are not left copying a shape you cannot see." },
      { type: "h2", text: "What to bring" },
      { type: "ul", items: [
        "Comfortable clothing you can move and bend in.",
        "A water bottle and a small towel.",
        "A mat if you have one — tell us in advance if you do not.",
        "A note of any medication, injury or condition your teacher should know about.",
        "Arrive around ten minutes early for your first session.",
      ]},
      { type: "h2", text: "Realistic expectations" },
      { type: "p", text: "You do not need to be flexible, fit or young to begin. In an early class you should expect to feel a bit awkward, to be corrected several times, and possibly to notice mild muscle soreness the next day. Progress is uneven and personal — some people notice they move more easily within a few weeks, others take longer. If you have a health condition, please get medical clearance first; yoga supports general wellbeing but does not replace qualified medical care." },
      { type: "h2", text: "How to enquire" },
      { type: "p", text: "Tell us your experience level, what you are hoping for, and which studio or format suits you. We will suggest a starting point rather than push you into the most expensive option. If you would rather begin from home, our live online classes follow the same teaching approach." },
    ],
    related: [
      { label: "Programs & Pricing", to: "/programs" },
      { label: "Yoga for Beginners", to: "/yoga-for-beginners" },
      { label: "Why traditional Hatha still matters", to: "/blog/why-traditional-hatha-still-matters" },
      { label: "About Master Anil", to: "/about" },
    ],
    faqs: [
      { q: "Do I need experience to join a class in Hai Duong?", a: "No. Beginners are expected and the teacher gives verbal corrections throughout the session." },
      { q: "Which studio has aerial yoga?", a: "Aerial yoga is available at Studio 1, Yog Jivan Sanctuary. It is not offered at Studio 2." },
      { q: "Can I try a class before committing?", a: "Please contact us to discuss options for your situation. The free introductory offer applies to the live online group classes." },
    ],
    cta: {
      title: "Start with the right class for you",
      sub: "Tell us your experience level and schedule, and we will suggest a sensible starting point.",
      primary: { label: "See programs & pricing", to: "/programs" },
      secondary: { label: "Contact the studio", to: "/contact", hash: "consultation" },
    },
  },
  {
    slug: "private-online-yoga-vs-group-classes",
    cat: "Comparison",
    cluster: "comparison",
    primaryKeyword: "private online yoga vs group classes",
    title: "Private online yoga vs small-group classes: which format fits you?",
    seoTitle: "Private Online Yoga vs Group Classes",
    excerpt:
      "A straightforward comparison of attention, scheduling, pace, privacy, community and cost so you can choose the format that suits your situation.",
    metaDescription:
      "Compare private 1-on-1 online yoga with live small-group classes at Yog Jivan: attention, scheduling, pace, privacy, community and how pricing works.",
    read: "8 min",
    date: "2026-08-06",
    keyTakeaways: [
      "Live group classes are 60 minutes with a maximum of eight students.",
      "Private sessions are 60 minutes, entirely built around one person, with pricing confirmed by enquiry.",
      "The two formats can be combined: group for routine, private for specific work.",
    ],
    body: [
      { type: "p", text: "Both formats are live and both are 60 minutes. Live small-group classes are led by Master Anil Choudhary; private 1-on-1 sessions are taught by a matched Yog Jivan teacher, and sessions are generally kept with the same teacher for continuity. The difference is how much of the session is shaped around you, and how much flexibility you need in scheduling. Here is a plain comparison." },
      { type: "h2", text: "Attention" },
      { type: "p", text: "In a live group class the cap is eight students, which is small enough for the teacher to see everyone and give verbal corrections by name during the session. In a private session, all the attention is on you: every posture can be adjusted, repeated or replaced on the spot." },
      { type: "h2", text: "Scheduling" },
      { type: "p", text: "Group classes run at fixed times, which is helpful if you want the discipline of a set slot and unhelpful if your work hours move. Private sessions are scheduled by arrangement, which suits shift workers, parents, frequent travellers and people working across time zones." },
      { type: "h2", text: "Pace and content" },
      { type: "ul", items: [
        "Group: a shared sequence with modifications offered as needed. Predictable structure.",
        "Private: the sequence is chosen for your experience, comfort limits and goals, and can change mid-session.",
        "Group: you progress alongside others, which some people find motivating.",
        "Private: you progress at your own rate without waiting or rushing.",
      ]},
      { type: "h2", text: "Privacy" },
      { type: "p", text: "Group classes ask for camera on, because real-time posture correction is the reason the class is live rather than recorded; we explain how that works before you join. If practising visibly in front of other students is uncomfortable for you — a common and reasonable preference — a private session removes that entirely." },
      { type: "h2", text: "Community" },
      { type: "p", text: "The group format offers something private work cannot: familiar faces, shared routine, and the quiet accountability of being noticed when you miss a week. For many students that is the deciding factor." },
      { type: "h2", text: "How pricing is presented" },
      { type: "p", text: "Live online group membership plans are published on the online classes page, so you can compare them yourself. Private session pricing is confirmed by enquiry, because it depends on frequency, format and scheduling. We do not publish a private price we would then have to qualify." },
      { type: "h2", text: "A simple way to decide" },
      { type: "ul", items: [
        "Want routine, structure and a lower published price? Start with the live group class.",
        "Have a specific limitation, an irregular schedule, or a strong preference for one-to-one work? Start private.",
        "Not sure? Many students do group classes weekly and book occasional private sessions to work on something specific.",
      ]},
      { type: "p", text: "If you are new to online practice altogether, it is worth reading what happens in a first live online class before deciding." },
    ],
    related: [
      { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "What happens in your first live online class", to: "/blog/first-live-online-yoga-class" },
      { label: "About Master Anil", to: "/about" },
    ],
    faqs: [
      { q: "How many students are in a live group class?", a: "A maximum of eight, so the teacher can still give individual verbal corrections." },
      { q: "Why is private pricing not published?", a: "It depends on frequency, format and scheduling, so we confirm it by enquiry rather than publish a figure that would need qualifying." },
      { q: "Can I switch between formats?", a: "Yes. Many students keep a group routine and add private sessions when they want to work on something specific." },
    ],
    cta: {
      title: "Choose the format that fits your week",
      sub: "Live group classes capped at eight, or fully individual 60-minute private sessions.",
      primary: { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      secondary: { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
    },
  },
  {
    slug: "first-live-online-yoga-class",
    cat: "Online",
    cluster: "online",
    primaryKeyword: "first live online yoga class",
    title: "What happens in your first live online yoga class?",
    seoTitle: "Your First Live Online Yoga Class",
    excerpt:
      "From the 15-minute onboarding conversation to the 60-minute class itself — exactly what to expect before, during and after your first live online session.",
    metaDescription:
      "A step-by-step walkthrough of your first live online yoga class with Yog Jivan: onboarding, setup, camera, the 60-minute class, languages and catch-up.",
    read: "8 min",
    date: "2026-08-06",
    keyTakeaways: [
      "A short 15-minute onboarding and practice-safety conversation comes first.",
      "Classes are 60 minutes with a maximum of eight students and real-time verbal guidance.",
      "Members can catch up on a missed class recording for 48 hours.",
    ],
    body: [
      { type: "p", text: "Your first live online class with Yog Jivan starts before the class itself. There is a short 15-minute onboarding and practice-safety conversation, then a 60-minute live session with a maximum of eight students. Here is the full sequence so nothing is a surprise." },
      { type: "h2", text: "Step 1 — the 15-minute onboarding conversation" },
      { type: "p", text: "This is a short conversation, not a sales call. We ask about your practice experience, current activity, any relevant injuries or limitations, and what you want from the class. It also gives us a chance to check your setup and answer questions. If your situation needs medical clearance first, we will say so." },
      { type: "h2", text: "Step 2 — setting up your space" },
      { type: "ul", items: [
        "Enough clear floor space to lie down and extend your arms in all directions.",
        "A device — phone, tablet or laptop — placed so your whole body is visible.",
        "A mat, plus any household items you might use as props, such as a firm cushion or a belt.",
        "Reasonable lighting in front of you rather than behind you.",
        "A stable internet connection and audio you can hear clearly.",
      ]},
      { type: "h2", text: "Step 3 — why the camera matters" },
      { type: "p", text: "Camera on is expected in live classes. It is the only way a teacher can see your alignment and correct it during the session, which is the entire reason for practising live rather than following a recording. We explain framing and privacy during onboarding, and you can position your device so only your practice space is visible." },
      { type: "h2", text: "Step 4 — the class itself" },
      { type: "p", text: "Classes run 60 minutes. The group is capped at eight students so Master Anil can watch each person and give verbal guidance by name as the session moves. Sessions are taught in English, Vietnamese and Hindi. A typical class opens with warming movement, works through standing and seated postures at a level suitable for the group, then finishes with breathing practice and rest." },
      { type: "h2", text: "Step 5 — questions and modifications" },
      { type: "p", text: "You can ask questions. If a posture does not suit your body on the day, say so and you will be given an alternative. Nothing in a Yog Jivan class requires you to push into pain." },
      { type: "h2", text: "If you miss a class" },
      { type: "p", text: "Members can access a recording of a missed class for 48 hours, so an unexpected work meeting does not break the week. Recordings are a catch-up option, not a replacement for live correction." },
      { type: "h2", text: "The introductory offer" },
      { type: "p", text: "New students can start with three days of free live group access plus one complimentary private session. No card is required, and there is one introductory offer per new student. The onboarding conversation happens before your first live class." },
    ],
    related: [
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "Setting up your camera and space", to: "/blog/online-yoga-camera-setup" },
      { label: "Private online yoga vs group classes", to: "/blog/private-online-yoga-vs-group-classes" },
      { label: "About Master Anil", to: "/about" },
    ],
    faqs: [
      { q: "Do I have to keep my camera on?", a: "Camera on is expected in live classes, because it is what makes real-time posture correction possible. We explain framing and privacy during onboarding." },
      { q: "What if I miss a class?", a: "Members can watch the recording of a missed class for 48 hours." },
      { q: "Which languages are classes taught in?", a: "English, Vietnamese and Hindi." },
    ],
    cta: {
      title: "Start with the live online classes",
      sub: "60 minutes, maximum eight students, real-time guidance from Master Anil.",
      primary: { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      secondary: { label: "Ask us a question", to: "/contact", hash: "consultation" },
    },
  },
  {
    slug: "live-online-yoga-vs-youtube",
    cat: "Comparison",
    cluster: "comparison",
    primaryKeyword: "live online yoga vs youtube",
    title: "Live online yoga vs YouTube videos: what is the difference?",
    seoTitle: "Live Online Yoga vs YouTube Videos",
    excerpt:
      "Free yoga videos are genuinely useful. Here is an honest comparison of feedback, pacing, safety, consistency, convenience and cost.",
    metaDescription:
      "An honest comparison of free YouTube yoga videos and live online classes: feedback, pacing, safety awareness, consistency, convenience and cost.",
    read: "7 min",
    date: "2026-08-06",
    keyTakeaways: [
      "Free videos are a legitimate way to practise, especially for experienced students.",
      "The main thing a video cannot do is see you and correct you.",
      "Live classes suit beginners, people with limitations, and anyone who struggles with consistency alone.",
    ],
    body: [
      { type: "p", text: "Free yoga videos have introduced more people to practice than any studio ever could, and we are not going to pretend otherwise. The useful question is not which is better in general, but which suits your situation right now. Here is a fair comparison." },
      { type: "h2", text: "Feedback" },
      { type: "p", text: "This is the real difference. A video cannot see your knee collapsing inward or your shoulders lifting toward your ears. A live teacher can, and can say so during the posture rather than after. In Yog Jivan's live classes the group is capped at eight students specifically so that verbal correction remains possible." },
      { type: "h2", text: "Pacing" },
      { type: "ul", items: [
        "Video: fixed pace, but you can pause and rewind freely.",
        "Live: the teacher adjusts to the people in the room, which usually means fewer rushed transitions.",
        "Video: you choose the level, which can mean overreaching without knowing it.",
        "Live: the level is set with your reported experience in mind.",
      ]},
      { type: "h2", text: "Safety awareness" },
      { type: "p", text: "A recorded class cannot know about your shoulder surgery, your pregnancy or your recent flare-up. A live teacher asks before you begin and offers alternatives during the session. If you have a health condition, get medical clearance first regardless of which format you choose." },
      { type: "h2", text: "Consistency" },
      { type: "p", text: "Videos require self-motivation every single day. A scheduled live class with a small group creates a commitment that many people find easier to keep. Neither approach works if the schedule is unrealistic in the first place." },
      { type: "h2", text: "Convenience and cost" },
      { type: "p", text: "Videos win on both: free, unlimited, available at 5am or midnight. Live classes cost money and happen at set times. That is a genuine trade-off, and for some students — experienced, self-aware, with a flexible body and a busy schedule — free videos are simply the right answer." },
      { type: "h2", text: "When a live class is worth it" },
      { type: "ul", items: [
        "You are a complete beginner and unsure whether you are doing postures correctly.",
        "You have an injury, health condition or limitation that needs modification.",
        "You have tried following videos and stopped after a few weeks.",
        "You want to ask questions and get answers about your own body.",
      ]},
      { type: "p", text: "A reasonable middle path is to use free videos on your own days and attend a live class weekly so someone can check what you are actually doing." },
    ],
    related: [
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "What happens in your first live online class", to: "/blog/first-live-online-yoga-class" },
      { label: "Building a home practice you will keep", to: "/blog/building-a-home-practice-you-will-keep" },
      { label: "About Master Anil", to: "/about" },
    ],
    faqs: [
      { q: "Are free yoga videos bad?", a: "No. They are a legitimate way to practise, particularly for experienced students. They simply cannot give you feedback." },
      { q: "Can a teacher really correct me over video?", a: "Yes, with the camera positioned so your whole body is visible. The class is capped at eight students so corrections can be given individually." },
    ],
    cta: {
      title: "Try a live class and see the difference",
      sub: "Live 60-minute classes with a maximum of eight students and real-time verbal guidance.",
      primary: { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      secondary: { label: "Yoga for Beginners", to: "/yoga-for-beginners" },
    },
  },
  {
    slug: "desk-worker-yoga-back-neck-shoulders",
    cat: "Mobility",
    cluster: "deskwork",
    primaryKeyword: "yoga for desk workers",
    title: "A practical yoga and mobility routine for desk workers",
    seoTitle: "Yoga for Desk Workers: Back, Neck, Shoulders",
    excerpt:
      "Simple movement breaks and a short daily routine for people who sit all day — with clear stop signs and no cure claims.",
    metaDescription:
      "A gentle yoga and mobility routine for desk workers covering back, neck and shoulders, plus workstation movement breaks and clear safety guidance.",
    read: "8 min",
    date: "2026-08-06",
    keyTakeaways: [
      "Frequent short movement breaks matter more than one long stretch session.",
      "Work within a comfortable range — this is general mobility, not treatment.",
      "Numbness, weakness or worsening pain means see a clinician, not a mat.",
    ],
    body: [
      { type: "p", text: "If you sit for most of the working day and your back, neck or shoulders feel stiff by the afternoon, the most useful change is usually frequency rather than intensity: short movement breaks through the day, plus a brief routine in the evening. What follows is general wellness guidance, not medical advice." },
      { type: "h2", text: "Movement breaks during the working day" },
      { type: "ul", items: [
        "Stand up briefly every 30 to 45 minutes, even for thirty seconds.",
        "Roll the shoulders backwards a few times and let the arms hang heavy.",
        "Turn the head slowly left and right within a comfortable range; do not force it.",
        "Stand and reach the arms overhead, then gently side bend each way.",
        "Take three slow breaths with a slightly longer exhale before returning to the screen.",
      ]},
      { type: "h2", text: "A short evening routine" },
      { type: "ul", items: [
        "Supported forward fold, knees soft — around 90 seconds.",
        "Gentle chest opening over a rolled towel or cushion — around 2 minutes.",
        "Slow seated twist, each side — around 60 seconds.",
        "Hip flexor lunge with the back knee down, each side — around 60 seconds.",
        "Legs resting up against a wall or on a chair — 3 to 5 minutes.",
        "Quiet breathing to finish — 2 minutes.",
      ]},
      { type: "h2", text: "Workstation basics" },
      { type: "p", text: "Screen roughly at eye level, feet supported, elbows near your sides, and the chair adjusted so you are not perching forward. No setup removes the need to move; it simply makes sitting less demanding between breaks." },
      { type: "h2", text: "Stop signs" },
      { type: "p", text: "Stop and speak to a doctor or physiotherapist if you experience numbness or tingling down an arm or leg, weakness, pain following an accident, pain that is getting steadily worse, night pain that wakes you, or any loss of bladder or bowel control. A mobility routine is not the right response to those symptoms." },
      { type: "h2", text: "Where a teacher helps" },
      { type: "p", text: "Generic routines assume a generic body. If something in the list above consistently aggravates you, a live class lets a teacher watch what you are doing and change it. Our back-focused guidance explains how we adapt practice for people with existing discomfort, and private 60-minute sessions — in studio or online — build the routine entirely around you." },
      { type: "h2", text: "Fitting it into a working week" },
      { type: "ul", items: [
        "Movement breaks daily — they cost almost nothing.",
        "The evening routine three or four times a week.",
        "One or two live classes weekly for correction and structure.",
        "Adjust rather than abandon when the week gets busy.",
      ]},
    ],
    related: [
      { label: "Yoga for Back Pain", to: "/yoga-for-back-pain" },
      { label: "Private 1-on-1 Yoga", to: "/private-online-yoga" },
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "Daily 12-minute spine mobility routine", to: "/blog/yoga-for-spine-longevity-12-minutes" },
    ],
    faqs: [
      { q: "How often should desk workers move?", a: "A brief break every 30 to 45 minutes is a practical target. Frequency matters more than the length of each break." },
      { q: "Will this fix my back pain?", a: "We cannot promise that. Gentle movement suits many people for general stiffness, but persistent or severe pain needs assessment by a clinician." },
    ],
    cta: {
      title: "Get the routine adjusted to your body",
      sub: "Live classes and private 60-minute sessions, in studio in the Hai Duong urban area or online.",
      primary: { label: "Yoga for Back Pain", to: "/yoga-for-back-pain" },
      secondary: { label: "Private 1-on-1 Yoga", to: "/private-online-yoga" },
    },
  },
  {
    slug: "online-yoga-camera-setup",
    cat: "Online",
    cluster: "online",
    primaryKeyword: "online yoga camera setup",
    title: "How to set up your camera and space for live online yoga",
    seoTitle: "Camera & Space Setup for Online Yoga",
    excerpt:
      "Device placement, framing, lighting, floor space, props, audio and privacy — a practical checklist so your teacher can actually see and correct you.",
    metaDescription:
      "A practical setup guide for live online yoga: camera framing, lighting, floor space, mat and props, internet and audio, privacy and a pre-class checklist.",
    read: "7 min",
    date: "2026-08-06",
    keyTakeaways: [
      "Aim for full-body framing from the side or a front-diagonal angle.",
      "Light in front of you, not behind — backlighting makes you a silhouette.",
      "Household items work fine as props; you do not need to buy equipment.",
    ],
    body: [
      { type: "p", text: "Live online yoga only works if the teacher can see you. A few minutes of setup makes the difference between receiving real corrections and effectively watching a video. Here is how to arrange your device and space." },
      { type: "h2", text: "Which device to use" },
      { type: "p", text: "A phone, tablet or laptop all work. A laptop is usually easiest because it sits stably and the screen is large enough to see the teacher. A phone is fine when propped at a decent height — a stack of books or a small stool works. Whatever you use, put it in landscape orientation and make sure it is charged or plugged in." },
      { type: "h2", text: "Framing" },
      { type: "ul", items: [
        "Place the camera 2 to 3 metres away if you can, so your whole mat is in frame.",
        "Set the lens at roughly knee to hip height rather than on the floor.",
        "Use a side or front-diagonal angle — this shows alignment better than straight-on.",
        "Check that your head and feet both stay in frame when you stand and when you lie down.",
      ]},
      { type: "h2", text: "Lighting" },
      { type: "p", text: "Light should come from in front of you. A window behind you turns you into a silhouette and the teacher will see nothing useful. If your room is dim, a lamp facing you from the front is enough." },
      { type: "h2", text: "Floor space" },
      { type: "p", text: "You need enough room to lie down and stretch your arms out in every direction without hitting furniture. Clear the area before class rather than mid-session, and check the floor is not slippery under your mat." },
      { type: "h2", text: "Mat and props" },
      { type: "ul", items: [
        "A non-slip mat is the one item worth having.",
        "A firm cushion or folded blanket instead of a bolster.",
        "A belt, scarf or towel instead of a yoga strap.",
        "Two thick books instead of blocks.",
        "A sturdy chair for supported or seated variations.",
      ]},
      { type: "h2", text: "Internet and audio" },
      { type: "p", text: "Sit near the router or use a wired connection if you can. Test your speakers before class — you need to hear a correction called out while you are facing away from the screen. Headphones can help in a noisy home, but choose ones that stay put when you move." },
      { type: "h2", text: "Privacy" },
      { type: "p", text: "Camera on is expected in live classes, because it is what makes real-time correction possible. You control the frame: position the device so only your practice area is visible, use a plain wall as a background, and close the door if you would rather not have the household in shot. If practising on camera in a group is not for you, private 1-on-1 online sessions are an alternative." },
      { type: "h2", text: "Pre-class checklist" },
      { type: "ul", items: [
        "Device charged, propped, landscape, at knee-to-hip height.",
        "Whole body in frame standing and lying down.",
        "Light in front of you.",
        "Floor clear, mat down, props within reach.",
        "Audio tested, notifications silenced.",
        "Water nearby, joined a couple of minutes early.",
      ]},
    ],
    related: [
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      { label: "What happens in your first live online class", to: "/blog/first-live-online-yoga-class" },
    ],
    faqs: [
      { q: "Do I need a special camera?", a: "No. The camera in a phone, tablet or laptop is fine. Placement and lighting matter far more than camera quality." },
      { q: "Can I keep my camera off?", a: "Camera on is expected in live group classes so the teacher can correct your alignment. If that does not suit you, a private session is a better fit." },
      { q: "What if I do not own props?", a: "Household items work. A cushion, a belt or scarf, two books and a chair cover almost everything." },
    ],
    cta: {
      title: "Ready when you are",
      sub: "Live 60-minute online classes, maximum eight students, with real-time verbal guidance.",
      primary: { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      secondary: { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
    },
  },
];
