// Cleaned versions of the seven original journal articles.
// Original publication dates preserved; `updated` records the 2026-08-06 revision.
import type { BlogPost } from "@/lib/blog/types";

export const LEGACY_POSTS: BlogPost[] = [
  {
    slug: "why-traditional-hatha-still-matters",
    cat: "Yoga",
    cluster: "beginner",
    primaryKeyword: "traditional hatha yoga",
    title: "Why traditional Hatha still matters",
    seoTitle: "Traditional Hatha Yoga: Why It Still Matters",
    excerpt:
      "Classical Hatha is slower on purpose. Here is what it actually involves, why it suits beginners, and how it prepares you for faster styles.",
    metaDescription:
      "What traditional Hatha yoga is, how it differs from Vinyasa, and why a slower alignment-led foundation suits beginners — explained by Master Anil Choudhary.",
    read: "6 min",
    date: "2026-04-12",
    updated: "2026-08-06",
    keyTakeaways: [
      "Hatha is a steady practice of posture, breathing, and stillness rather than a fast workout.",
      "The slower pace gives you time to learn alignment before speed is added.",
      "It is a practical starting point for beginners and for people returning after a long break.",
    ],
    body: [
      { type: "p", text: "Traditional Hatha yoga is a slower, hold-based practice that combines postures, breathing and periods of stillness. If you are choosing a first style, it is usually the most practical place to begin, because the pace leaves room to learn what each posture should feel like before any faster sequencing is introduced." },
      { type: "h2", text: "What traditional Hatha actually is" },
      { type: "p", text: "In the classical sense, Hatha is a structured practice of asana (posture), pranayama (breathing practice), and dhyana (meditative attention). Postures are held for several breaths rather than flowed through. That does not mean it is always easy — long holds can be demanding — but the effort is internal and controlled rather than driven by tempo." },
      { type: "h2", text: "How Hatha differs from Vinyasa" },
      { type: "ul", items: [
        "Hatha holds a posture and works on it; Vinyasa links postures into a continuous flow.",
        "Hatha gives a teacher time to see and correct alignment; a flow class moves on quickly.",
        "Hatha typically uses fewer transitions, which lowers the chance of rushing into an unfamiliar shape.",
        "Both are valid. Many students practise Hatha first and add flow later.",
      ]},
      { type: "h2", text: "Why the slower foundation is useful" },
      { type: "p", text: "Three things become much easier when a class is not rushing. First, you notice where your own range genuinely ends, instead of borrowing movement from somewhere else in the body. Second, breathing becomes something you can actively work with rather than background noise. Third, a teacher can offer a correction and you have time to apply it — which is the whole point of a live class instead of a video." },
      { type: "p", text: "A teaching principle we come back to at Yog Jivan: the pose is not the practice — the breath inside the pose is." },
      { type: "h2", text: "Who it suits" },
      { type: "p", text: "Hatha suits complete beginners, people who describe themselves as not flexible, desk workers who want to move more comfortably, and anyone returning after injury, illness or a long gap — with medical clearance where a health condition is involved. Many students find a steady practice supportive for general wellbeing; individual experience varies and yoga does not replace care from a qualified health professional." },
      { type: "h2", text: "How to start" },
      { type: "ul", items: [
        "Choose a class where the teacher can actually see you and speak to you during the session.",
        "Tell the teacher about any injury, health condition or recent surgery before your first class.",
        "Aim for two or three short sessions a week rather than one long one.",
        "Give it several weeks before deciding whether the style fits you.",
      ]},
      { type: "p", text: "At Yog Jivan, both the studio beginner path and the live online classes start from this Hatha foundation. Studio classes are taught by the Yog Jivan teaching team; live small-group online classes are led personally by Master Anil Choudhary." },
    ],
    related: [
      { label: "Yoga for Beginners", to: "/yoga-for-beginners" },
      { label: "Yoga classes in Hai Duong: a beginner's guide", to: "/blog/yoga-classes-hai-duong-beginners-guide" },
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "About Master Anil", to: "/about" },
    ],
    faqs: [
      { q: "Is Hatha yoga good for beginners?", a: "It is a sensible starting point. The slower pace means you can learn alignment and breathing before speed is added." },
      { q: "How is Hatha different from Vinyasa?", a: "Hatha holds postures with the breath; Vinyasa links postures in a continuous flow. Many students find Hatha a more comfortable introduction." },
      { q: "Do I need to be flexible to start?", a: "No. Flexibility is an outcome of practice, not a requirement for joining a beginner class." },
    ],
    cta: {
      title: "Begin with the foundations",
      sub: "Beginner-friendly studio classes in the Hai Duong urban area with the Yog Jivan teaching team, and live online classes led by Master Anil.",
      primary: { label: "Yoga for Beginners", to: "/yoga-for-beginners" },
      secondary: { label: "See programs & pricing", to: "/programs" },
    },
  },
  {
    slug: "yoga-for-spine-longevity-12-minutes",
    cat: "Health",
    cluster: "deskwork",
    primaryKeyword: "daily spine mobility routine",
    title: "A daily 12-minute spine mobility routine",
    seoTitle: "A Daily 12-Minute Spine Mobility Routine",
    excerpt:
      "A short, gentle routine that moves the spine through its main directions — with clear guidance on when to stop and when to see a clinician instead.",
    metaDescription:
      "A gentle 12-minute daily spine mobility routine for stiff backs and desk workers, with safety guidance on when to stop and seek medical advice.",
    read: "6 min",
    date: "2026-05-03",
    updated: "2026-08-06",
    keyTakeaways: [
      "A short daily routine is easier to keep than a long weekly one.",
      "The spine benefits from gentle movement in several directions, within a comfortable range.",
      "Stop and seek medical advice for sharp pain, numbness, weakness or symptoms that keep worsening.",
    ],
    body: [
      { type: "p", text: "If your back feels stiff after long hours at a desk, a short daily mobility routine is a reasonable place to start. This one takes around twelve minutes and moves the spine gently through its main directions. It is a general wellness routine, not a treatment plan, and it is not a substitute for assessment by a doctor or physiotherapist." },
      { type: "h2", text: "Before you begin" },
      { type: "ul", items: [
        "Work inside a comfortable range. Mild stretch is fine; sharp or radiating pain is not.",
        "Move slowly and breathe normally throughout.",
        "Stop if you feel numbness, tingling, weakness, dizziness or increasing pain.",
        "If you have a diagnosed spinal condition, recent injury or surgery, get medical clearance first and ask a teacher to adapt the routine.",
      ]},
      { type: "h2", text: "The routine" },
      { type: "ul", items: [
        "Gentle flexion — a supported forward fold or seated fold, about 90 seconds.",
        "Gentle extension — a small, comfortable backbend such as a low cobra, about 90 seconds.",
        "Side bend, left and right — around 60 seconds each side.",
        "Rotation, left and right — a slow seated or reclined twist, around 60 seconds each side.",
        "Decompression — a supported rest that lets the spine lengthen, about two minutes.",
        "Quiet breathing in a neutral position to finish, about two to three minutes.",
      ]},
      { type: "h2", text: "Why short and daily" },
      { type: "p", text: "Consistency is usually the deciding factor. A twelve-minute routine tends to get done on a busy day; a forty-five-minute one often does not. Many students find that a short daily habit feels more manageable and easier to sustain than occasional long sessions. What you should expect varies from person to person, and there is no fixed timeline for how you will feel." },
      { type: "h2", text: "Signs to see a clinician instead" },
      { type: "p", text: "Movement is not the right first step for everything. Please see a doctor rather than starting a routine if you have unexplained pain, pain following significant trauma, numbness or weakness in a leg or arm, loss of bladder or bowel control, fever with back pain, or pain that consistently wakes you at night. These need proper assessment." },
      { type: "h2", text: "Getting it adapted to you" },
      { type: "p", text: "If you already have back discomfort, a general routine can only take you so far. In a private session, your matched Yog Jivan teacher can watch how you actually move, remove anything that provokes your symptoms, and adjust the sequence to your situation. Private sessions are 60 minutes, in studio or live online, with scheduling and pricing confirmed by enquiry." },
    ],
    related: [
      { label: "Yoga for Back Pain", to: "/yoga-for-back-pain" },
      { label: "A practical routine for desk workers", to: "/blog/desk-worker-yoga-back-neck-shoulders" },
      { label: "Private 1-on-1 Yoga", to: "/private-online-yoga" },
      { label: "About Master Anil", to: "/about" },
    ],
    faqs: [
      { q: "Can twelve minutes a day help a stiff back?", a: "Many people find regular gentle movement helpful for general stiffness. Results vary, and persistent or severe pain should be assessed by a clinician." },
      { q: "Should I do this if I have a disc problem?", a: "Not without medical clearance. Some movements may need to be modified or left out, so speak to your doctor and ask a teacher to adapt the routine." },
    ],
    cta: {
      title: "Have the routine adapted to your back",
      sub: "A private 60-minute session lets your matched Yog Jivan teacher see how you move and adjust the sequence to you.",
      primary: { label: "Private 1-on-1 Yoga", to: "/private-online-yoga" },
      secondary: { label: "Yoga for Back Pain", to: "/yoga-for-back-pain" },
    },
  },
  {
    slug: "the-breath-you-didnt-know-you-were-holding",
    cat: "Wellness",
    cluster: "wellness",
    primaryKeyword: "beginner breathing exercise",
    title: "A simple breathing practice for beginners",
    seoTitle: "A Simple Two-Minute Breathing Practice",
    excerpt:
      "Many people breathe shallowly through a busy day. Here is a comfortable, low-risk breathing practice you can try, and how to keep it safe.",
    metaDescription:
      "A simple beginner breathing practice: how to notice shallow breathing, a comfortable two-minute exercise, and safety guidance from Yog Jivan.",
    read: "4 min",
    date: "2026-05-20",
    updated: "2026-08-06",
    keyTakeaways: [
      "A quick hand-on-chest check tells you whether your breathing is mostly upper-chest.",
      "A slightly longer exhale, practised comfortably, is an easy place to start.",
      "Never force the breath. Stop if you feel light-headed or uncomfortable.",
    ],
    body: [
      { type: "p", text: "If you want one small practice to start with, start with breathing. It needs no equipment, takes two minutes, and can be done at a desk. What follows is a comfortable beginner practice — not a therapy, and not something that will produce a guaranteed result." },
      { type: "h2", text: "A simple way to notice your pattern" },
      { type: "p", text: "Sit upright. Place one hand on your chest and one on your belly. Breathe normally for around thirty seconds and just observe. If only the upper hand moves noticeably, your breathing is sitting mostly in the chest. That is common, especially during a busy day, and it is something you can work with gently." },
      { type: "h2", text: "The practice" },
      { type: "ul", items: [
        "Inhale through the nose for a comfortable count of four, letting the lower ribs and belly expand.",
        "Exhale through the nose for a count of six, slightly longer than the inhale.",
        "Keep both counts easy. If four and six feel strained, try three and four.",
        "Continue for around two minutes, once or twice a day.",
      ]},
      { type: "h2", text: "Keeping it safe" },
      { type: "p", text: "Breathing practices should feel calm rather than effortful. Stop if you become light-headed, breathless or anxious, and return to normal breathing. If you have a respiratory or cardiac condition, are pregnant, or have a history of panic attacks, check with your doctor first and let your teacher know so the practice can be adapted." },
      { type: "h2", text: "What to expect" },
      { type: "p", text: "People respond differently. Some notice they feel a little steadier after a session; others notice nothing at first and find it becomes more useful with repetition. We would rather say that plainly than promise a specific change on a specific schedule. Treat it as a small daily habit, not a fix." },
      { type: "h2", text: "Where breathing fits in a class" },
      { type: "p", text: "In Yog Jivan classes, breathing practice is taught alongside movement rather than as an add-on, and a live teacher can hear and see whether you are straining. That feedback is the main reason people join a live class instead of following a recording." },
    ],
    related: [
      { label: "Yoga for Stress & Anxiety", to: "/yoga-for-stress" },
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "About Master Anil", to: "/about" },
    ],
    faqs: [
      { q: "How long before I notice a change?", a: "It varies from person to person. Some people notice a small settling effect early; others find it takes regular repetition. We do not promise a fixed timeline." },
      { q: "Is breathing practice safe for everyone?", a: "Comfortable, unforced breathing suits most people, but anyone with a respiratory or cardiac condition, or who is pregnant, should check with a doctor and tell their teacher." },
    ],
    cta: {
      title: "Learn breathing with live guidance",
      sub: "Breathing practice is taught inside every live class, so a teacher can tell if you are straining.",
      primary: { label: "Yoga for Stress", to: "/yoga-for-stress" },
      secondary: { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
    },
  },
  {
    slug: "beginners-guide-to-20-minutes-of-stillness",
    cat: "Meditation",
    cluster: "wellness",
    primaryKeyword: "meditation for beginners",
    title: "Meditation for beginners: 5, 10 or 20 minutes",
    seoTitle: "Meditation for Beginners: 5, 10 or 20 Minutes",
    excerpt:
      "You do not need a set session length to begin. Here are three simple frameworks — five, ten and twenty minutes — and what usually happens in the first weeks.",
    metaDescription:
      "A beginner's guide to meditation with practical 5, 10 and 20 minute frameworks, common early experiences, and how to build a habit that lasts.",
    read: "6 min",
    date: "2026-06-01",
    updated: "2026-08-06",
    keyTakeaways: [
      "Any consistent length is better than an ambitious length you skip.",
      "Five minutes daily is a legitimate starting point.",
      "Restlessness in early sessions is normal and not a sign of failure.",
    ],
    body: [
      { type: "p", text: "Beginners often ask how long they should meditate. There is no single correct number. Pick the length you can repeat most days — five minutes done daily is more useful than twenty minutes attempted twice a month." },
      { type: "h2", text: "A five-minute framework" },
      { type: "ul", items: [
        "One minute: settle your posture and let the exhale lengthen slightly.",
        "Three minutes: rest attention on the breath at the nostrils; when the mind wanders, return without judgement.",
        "One minute: sit quietly before standing up.",
      ]},
      { type: "h2", text: "A ten-minute framework" },
      { type: "ul", items: [
        "Two minutes: settle and scan the body for obvious tension.",
        "Six minutes: follow the breath, counting exhales one to ten and restarting.",
        "Two minutes: sit without an anchor and simply notice.",
      ]},
      { type: "h2", text: "A twenty-minute framework" },
      { type: "ul", items: [
        "Minutes 0–5: settle the body, lengthen the exhale.",
        "Minutes 5–15: watch the breath. Return each time attention drifts.",
        "Minutes 15–20: rest attention without an anchor.",
      ]},
      { type: "h2", text: "What the first two weeks usually feel like" },
      { type: "p", text: "Expect restlessness, boredom, an active mind, and occasional moments of clarity — sometimes within the same session. None of that indicates you are doing it wrong. The instruction is simply to notice and return. Experiences differ, and meditation is not a treatment for a mental health condition; if you are managing one, speak to your clinician about what suits you." },
      { type: "h2", text: "Making it stick" },
      { type: "ul", items: [
        "Attach it to something you already do daily, such as after brushing your teeth.",
        "Keep the same time and place so the decision is already made.",
        "Use a timer so you are not checking the clock.",
        "Count consistency, not session quality.",
      ]},
      { type: "p", text: "In Yog Jivan classes, short seated practice is included at the end of a session, which is often an easier way in than sitting alone at home from day one." },
    ],
    related: [
      { label: "Yoga for Stress & Anxiety", to: "/yoga-for-stress" },
      { label: "A simple breathing practice", to: "/blog/the-breath-you-didnt-know-you-were-holding" },
      { label: "About Master Anil", to: "/about" },
    ],
    faqs: [
      { q: "How long should a beginner meditate?", a: "Start with whatever you can repeat most days — five minutes is a legitimate starting point. Length matters less than consistency." },
      { q: "Is it normal for my mind to be busy?", a: "Yes. Noticing that attention has wandered and returning to the breath is the practice itself." },
    ],
    cta: {
      title: "Practise with guidance",
      sub: "Live classes end with a short guided seated practice — an easier entry point than sitting alone.",
      primary: { label: "Yoga for Stress", to: "/yoga-for-stress" },
      secondary: { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
    },
  },
  {
    slug: "yoga-for-sustainable-fat-loss",
    cat: "Weight Loss",
    cluster: "wellness",
    primaryKeyword: "yoga for weight loss",
    title: "Yoga and sustainable weight management",
    seoTitle: "Yoga and Sustainable Weight Management",
    excerpt:
      "Yoga is not a quick weight-loss method. Here is a realistic view of how a steady practice can support strength, consistency and better daily habits.",
    metaDescription:
      "A realistic look at yoga and weight management: what a steady practice can support, what it cannot promise, and how to build a schedule you keep.",
    read: "7 min",
    date: "2026-06-18",
    updated: "2026-08-06",
    keyTakeaways: [
      "Yoga supports strength, mobility and consistency; it is not a rapid weight-loss method.",
      "A sustainable weekly rhythm beats short bursts of intense training.",
      "Nutrition advice should come from a qualified dietitian or your doctor.",
    ],
    body: [
      { type: "p", text: "If you are considering yoga for weight management, the honest answer is that it can be a useful part of an active, consistent lifestyle — not a shortcut, and not something that produces a predictable number on the scale. What a regular practice tends to support is strength, mobility, movement you can maintain, and a calmer relationship with exercise." },
      { type: "h2", text: "What a steady practice can support" },
      { type: "ul", items: [
        "General strength and mobility, which make other activity easier.",
        "A routine you can keep, because sessions are joint-friendly and repeatable.",
        "Winding down at the end of the day, which many students find helps their sleep habits.",
        "Body awareness, which some people find useful when building steadier daily habits.",
      ]},
      { type: "h2", text: "What it cannot promise" },
      { type: "p", text: "We do not promise a weight loss figure, a weekly rate, or a fixed timeline, and we do not claim yoga changes your hormones in a specific measurable way. Weight is influenced by many factors — nutrition, sleep, medical conditions, medication, genetics and daily activity. Anyone offering a guaranteed number is selling rather than teaching." },
      { type: "h2", text: "A weekly rhythm that people actually keep" },
      { type: "ul", items: [
        "Three to four sessions a week, mixing more active classes with slower restorative ones.",
        "Short daily movement on non-class days, even ten minutes.",
        "Regular walking or other activity you enjoy alongside yoga.",
        "A realistic review every few weeks — how you feel, how consistent you have been, what needs adjusting.",
      ]},
      { type: "h2", text: "About nutrition" },
      { type: "p", text: "We do not provide personalised nutrition plans or prescribe diets. For individual dietary guidance, please speak to a registered dietitian or your doctor, especially if you have a medical condition, are pregnant, or are taking medication." },
      { type: "h2", text: "Choosing a format" },
      { type: "p", text: "Studio group classes suit people who want the routine of leaving the house. Live small-group online classes suit people with variable schedules, and they cap at eight students so the teacher can still give verbal correction. If you would rather have the pace built entirely around you, private 60-minute sessions are available in studio or online, arranged by enquiry." },
    ],
    related: [
      { label: "Yoga for Weight Loss", to: "/yoga-for-weight-loss" },
      { label: "Private 1-on-1 Yoga", to: "/private-online-yoga" },
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "About Master Anil", to: "/about" },
    ],
    faqs: [
      { q: "How much weight will I lose with yoga?", a: "We do not give a figure. Weight change depends on many personal factors, and any specific promise would be misleading." },
      { q: "Do I need hot yoga to lose weight?", a: "No. Sweating is not the same as fat loss. A consistent practice you can maintain is more useful than an intense one you abandon." },
    ],
    cta: {
      title: "Build a schedule you can keep",
      sub: "Compare studio memberships, live online classes and private sessions.",
      primary: { label: "See programs & pricing", to: "/programs" },
      secondary: { label: "Yoga for Weight Loss", to: "/yoga-for-weight-loss" },
    },
  },
  {
    slug: "building-a-home-practice-you-will-keep",
    cat: "Lifestyle",
    cluster: "beginner",
    primaryKeyword: "home yoga practice habit",
    title: "Building a home yoga practice you will keep",
    seoTitle: "Build a Home Yoga Practice You Keep",
    excerpt:
      "Five practical habits that make a home practice survive a busy week — plus where a live class fits when motivation dips.",
    metaDescription:
      "Practical habits for building a home yoga practice that lasts: fixed timing, reducing friction, short sessions, teacher feedback and accountability.",
    read: "5 min",
    date: "2026-07-04",
    updated: "2026-08-06",
    keyTakeaways: [
      "Reduce friction: a mat left out is a mat used.",
      "Short and regular beats long and occasional.",
      "Some form of accountability makes a real difference when motivation dips.",
    ],
    body: [
      { type: "p", text: "Most people do not stop practising because yoga stopped working. They stop because the habit was never designed to survive a difficult week. Here are five practical habits that help." },
      { type: "h2", text: "1. Keep the time fixed" },
      { type: "p", text: "Practising at roughly the same time each day removes the daily decision. Early morning works for many people simply because fewer things have gone wrong yet, but the best time is the one you can repeat." },
      { type: "h2", text: "2. Reduce friction" },
      { type: "p", text: "Leave the mat out. Keep props in the same place. Have clothes ready. Every small obstacle between you and the first minute is a chance to skip." },
      { type: "h2", text: "3. Make sessions short enough to be plausible" },
      { type: "p", text: "Fifteen honest minutes done four times a week is a practice. An hour planned and skipped is not. You can always continue past fifteen minutes when you feel like it." },
      { type: "h2", text: "4. Get corrected sometimes" },
      { type: "p", text: "Home practice tends to drift. Attending a live class periodically — in studio or online — lets a teacher see what you are actually doing and adjust it. That feedback is what a recording cannot provide." },
      { type: "h2", text: "5. Have some accountability" },
      { type: "p", text: "A small class where the teacher notices your absence is a surprisingly effective commitment device. Yog Jivan's live online groups cap at eight students, so attendance is visible rather than anonymous." },
      { type: "h2", text: "A simple weekly template" },
      { type: "ul", items: [
        "Two live classes for correction and structure.",
        "Two or three short home sessions of fifteen to twenty minutes.",
        "One longer, slower session when time allows.",
        "One genuine rest day without guilt.",
      ]},
      { type: "p", text: "If you are still deciding what to practise at home, our beginner path covers the basic sequence and safety points to start with." },
    ],
    related: [
      { label: "Yoga for Beginners", to: "/yoga-for-beginners" },
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "Setting up your camera and space", to: "/blog/online-yoga-camera-setup" },
    ],
    faqs: [
      { q: "How often should I practise at home?", a: "Three to five short sessions a week is a realistic target for most people. Consistency matters more than length." },
      { q: "Do I still need classes if I practise at home?", a: "Not necessarily, but periodic live sessions help catch habits that quietly develop when nobody is watching." },
    ],
    cta: {
      title: "Add structure to your home practice",
      sub: "Live small-group classes of 60 minutes, capped at eight students, taught personally by Master Anil.",
      primary: { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      secondary: { label: "Yoga for Beginners", to: "/yoga-for-beginners" },
    },
  },
  {
    slug: "therapeutic-yoga-benefits",
    cat: "Health",
    cluster: "wellness",
    primaryKeyword: "personalised supportive yoga",
    title: "Personalised supportive yoga: what it is and what it is not",
    seoTitle: "Personalised Supportive Yoga Explained",
    excerpt:
      "How a personalised yoga session differs from a general class, what it can reasonably support, and where qualified medical care must come first.",
    metaDescription:
      "What personalised supportive yoga involves at Yog Jivan, how it differs from a general class, and the clear limits of what yoga can and cannot do.",
    read: "8 min",
    date: "2026-07-30",
    updated: "2026-08-06",
    keyTakeaways: [
      "A personalised session adapts the practice to you rather than fitting you to a class sequence.",
      "Yoga can support general wellbeing; it does not diagnose, treat or replace medical care.",
      "Some symptoms need a doctor first — we will say so rather than take the booking.",
    ],
    body: [
      { type: "p", text: "Personalised supportive yoga means a practice built around one person's needs, preferences and limitations rather than a single sequence delivered to a full room. At Yog Jivan this takes the form of private 60-minute sessions with a matched teacher from the Yog Jivan teaching team, in studio or live online. It is a wellness service. It is not medical treatment, and it does not diagnose or cure anything." },
      { type: "h2", text: "How it differs from a general class" },
      { type: "ul", items: [
        "The sequence is chosen for you rather than for the group.",
        "Movements that feel provocative or uncomfortable for you are left out or modified.",
        "Pace, props and rest are adjusted to your experience and energy on the day.",
        "You can ask questions throughout instead of holding them until the end.",
      ]},
      { type: "h2", text: "What a session involves" },
      { type: "ul", items: [
        "A conversation about your background, activity level, comfort limits and what you want from the practice.",
        "Gentle movement within your comfortable range, with real-time verbal guidance.",
        "Simple breathing practice and a period of rest.",
        "A short home sequence, usually 12 to 20 minutes, so the work continues between sessions.",
      ]},
      { type: "p", text: "A teaching principle we come back to at Yog Jivan: we are not teaching a pose, we are teaching the person in front of us, and the pose is only the instrument." },
      { type: "h2", text: "What it can reasonably support" },
      { type: "p", text: "Many students find that a steady, well-adapted practice helps them feel more comfortable moving, more aware of posture during the day, and calmer at the end of it. Those are the kinds of general wellbeing outcomes we can honestly describe. Individual experience varies, and we do not measure clinical outcomes, promise symptom reduction, or track medical baselines — that is the role of your healthcare team." },
      { type: "h2", text: "Where medical care must come first" },
      { type: "p", text: "Please see a doctor before booking if you have undiagnosed or worsening pain, a recent injury or surgery, numbness or weakness in a limb, loss of bladder or bowel control, fever alongside pain, an unstable cardiac condition, or a high-risk pregnancy. If your answers suggest you need assessment rather than a mat, we will say so and ask you to come back once you have clearance." },
      { type: "h2", text: "Group or private?" },
      { type: "p", text: "If you mainly want structure and routine, a group class is usually enough — our live online groups cap at eight students so verbal correction is still possible. If you have specific limitations, an unusual schedule, or you would simply rather not practise in a group, private sessions are the better fit. Private scheduling and pricing are confirmed by enquiry." },
      { type: "p", text: "Our condition-focused pages for back discomfort, stress and PCOD explain how the practice is adapted in each case, always alongside — never instead of — qualified medical care." },
    ],
    related: [
      { label: "Yoga for Back Pain", to: "/yoga-for-back-pain" },
      { label: "Yoga for Stress & Anxiety", to: "/yoga-for-stress" },
      { label: "Private 1-on-1 Yoga", to: "/private-online-yoga" },
      { label: "About Master Anil", to: "/about" },
    ],
    faqs: [
      { q: "Is this yoga therapy?", a: "We describe it as personalised supportive yoga. It adapts the practice to you, but it is not medical treatment and does not include clinical assessment or diagnosis." },
      { q: "Can I do a personalised session online?", a: "Yes. Private sessions are 60 minutes and run either in studio or live online, with the same real-time verbal guidance." },
      { q: "Do you replace my doctor or physiotherapist?", a: "No. Yoga supports general wellbeing alongside qualified medical care. Please keep your clinicians involved." },
    ],
    cta: {
      title: "Talk to us about a private session",
      sub: "Live 60-minute one-to-one sessions in studio or online. Scheduling and pricing confirmed by enquiry.",
      primary: { label: "Private 1-on-1 Yoga", to: "/private-online-yoga" },
      secondary: { label: "Contact the studio", to: "/contact", hash: "consultation" },
    },
  },
];
