// Private 1-on-1 online yoga content cluster.
// Every post supports /private-online-yoga and links back to it contextually.
// No invented students, outcomes, timelines, prices or credentials.
import type { BlogPost } from "@/lib/blog/types";

const PRIVATE_CTA = {
  title: "Private 1-on-1 online yoga",
  sub: "Tell us your level, your goals and when you like to practise. Scheduling and pricing are arranged by enquiry.",
  primary: { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
  secondary: { label: "Live Online Group Classes", to: "/online-yoga-classes" },
};

export const PRIVATE_POSTS: BlogPost[] = [
  {
    slug: "what-happens-in-a-private-online-yoga-session",
    cat: "Private Yoga",
    cluster: "private",
    primaryKeyword: "what happens in a private online yoga session",
    title: "What actually happens in a private online yoga session",
    seoTitle: "What Happens in a Private Online Yoga Session",
    excerpt:
      "A step-by-step walkthrough of a private 1-on-1 online yoga session: the intake conversation, camera setup, the 60 minutes themselves and what follows.",
    metaDescription:
      "Step by step through a private 1-on-1 online yoga session with Yog Jivan: intake conversation, camera and space setup, the 60-minute session and follow-up.",
    read: "7 min",
    date: "2026-08-08",
    keyTakeaways: [
      "Sessions run 60 minutes, live, with the same teacher each time.",
      "A short onboarding and health conversation happens before your first session.",
      "Camera on is required so your teacher can see and correct your alignment.",
    ],
    body: [
      { type: "p", text: "People often hesitate to book private online yoga because they cannot picture it. This is what a private 1-on-1 session with Yog Jivan actually involves, from the first conversation to the end of the hour." },
      { type: "h2", text: "Before your first session: a short conversation" },
      { type: "p", text: "We begin with a brief onboarding and health conversation of around fifteen minutes. It is not a sales call. Your teacher asks what you want from your practice, what you have done before, how much time you realistically have each week, and whether there is any injury, surgery, pregnancy, medication or medical condition that should shape the session. If something needs clearance from your doctor, we will say so." },
      { type: "h2", text: "Setting up your space and camera" },
      { type: "ul", items: [
        "Clear a space roughly the length of your mat plus arm span in each direction.",
        "Place the device side-on at about hip height, far enough back that your whole mat is in frame.",
        "Put the light in front of you rather than behind, so you are not a silhouette.",
        "Use headphones if the room echoes; hearing corrections clearly matters more than picture quality.",
      ]},
      { type: "p", text: "Camera on is required for private sessions. Without seeing you, a teacher can only narrate a class rather than correct one — which removes the reason for choosing private work. Sessions are not recorded unless you ask for a recording." },
      { type: "h2", text: "The 60 minutes" },
      { type: "p", text: "A typical hour opens with settling and breath awareness, moves through warming preparation, then into the main practice chosen for you — standing work, seated and floor work, or specific therapeutic sequences depending on your intake. Your teacher watches continuously and gives verbal cues by name: which knee, which shoulder, which direction. The session closes with slowing-down work, a breathing practice and rest." },
      { type: "h2", text: "How a private session differs from a group class" },
      { type: "ul", items: [
        "The sequence is chosen for your body and your goals, not for a room of eight people.",
        "You can stop and ask questions at any point.",
        "Postures are modified for you rather than announced as options.",
        "Timing is arranged around your schedule and timezone.",
      ]},
      { type: "h2", text: "After the session" },
      { type: "p", text: "Your teacher will usually suggest one or two things to practise between sessions — often short and specific rather than a long home routine. Because you keep the same teacher, the next session continues from where you left off instead of starting over." },
      { type: "h2", text: "What we do not promise" },
      { type: "p", text: "We do not promise a fixed number of sessions to a fixed result, and we do not treat yoga as a substitute for medical care. What we can commit to is live attention, honest correction and a practice that fits your situation." },
    ],
    related: [
      { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "Can an online teacher really correct your posture?", to: "/blog/can-an-online-yoga-teacher-correct-your-posture" },
      { label: "Private online yoga for complete beginners", to: "/blog/private-online-yoga-for-beginners" },
    ],
    faqs: [
      { q: "How long is a private online yoga session?", a: "Sixty minutes, taught live. The onboarding conversation before your first session is separate and takes about fifteen minutes." },
      { q: "Do I have to keep my camera on?", a: "Yes. Private sessions depend on your teacher being able to see your alignment. Sessions are not recorded unless you request it." },
      { q: "What equipment do I need?", a: "A mat and a stable device. A cushion, a belt or scarf, a chair and a couple of thick books cover most prop needs." },
      { q: "How much does a private session cost?", a: "Private scheduling and pricing are arranged by enquiry, because they depend on frequency and format." },
    ],
    cta: PRIVATE_CTA,
  },
  {
    slug: "can-an-online-yoga-teacher-correct-your-posture",
    cat: "Private Yoga",
    cluster: "private",
    primaryKeyword: "can an online yoga teacher correct your posture",
    title: "Can an online yoga teacher really correct your posture?",
    seoTitle: "Can an Online Yoga Teacher Correct Your Posture?",
    excerpt:
      "Yes — with the camera placed properly and a teacher watching live. Here is what online correction can see, what it cannot, and how to set your space up for it.",
    metaDescription:
      "How live online yoga correction works in practice: camera placement, what a teacher can and cannot see on screen, verbal cueing, and when in-studio is better.",
    read: "7 min",
    date: "2026-08-08",
    keyTakeaways: [
      "Live correction depends on camera angle far more than camera quality.",
      "Verbal, named cueing replaces hands-on adjustment and is often more durable.",
      "Some situations genuinely need in-person work — we will tell you when.",
    ],
    body: [
      { type: "p", text: "It is a fair question, and the honest answer is: yes, if the class is live and your teacher can see you properly. A pre-recorded video cannot correct anything at all. A live session with a side-on camera and a small class can." },
      { type: "h2", text: "What a teacher can see on screen" },
      { type: "ul", items: [
        "Spinal shape — rounding, over-arching, and where a bend is actually happening.",
        "Weight distribution through the feet and hands, and which side is loading more.",
        "Knee and elbow tracking relative to ankles and wrists.",
        "Shoulder position, neck tension and jaw clenching.",
        "Breath rhythm, holding, and where a posture stops being sustainable.",
      ]},
      { type: "h2", text: "What is harder to see" },
      { type: "p", text: "Subtle rotation, fine foot mechanics and internal sensation are harder through a screen. That is why your teacher will ask you questions during a private session rather than assume, and why we ask about pain rather than waiting for you to mention it." },
      { type: "h2", text: "Camera placement matters more than camera quality" },
      { type: "ul", items: [
        "Side-on, not front-on: the side view reveals spinal shape, which matters most.",
        "Hip height, roughly one and a half to two metres back, with the whole mat in frame.",
        "Light in front of you, not behind.",
        "Move the device for floor work if the frame cuts you off — your teacher will ask.",
      ]},
      { type: "h2", text: "Why verbal correction works" },
      { type: "p", text: "A hands-on adjustment moves you into a shape. A precise verbal cue teaches you to find it yourself, which is what you need when you practise alone. Our live group classes are capped at eight students so there is time for named, individual cueing, and private sessions give you the whole hour." },
      { type: "h2", text: "When in-person is genuinely better" },
      { type: "p", text: "Complex post-surgical rehabilitation, significant balance impairment, or anything where physical support is needed is better done in person, and ideally alongside your medical team. If your situation falls into that category we will say so during the onboarding conversation rather than take the booking." },
    ],
    related: [
      { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      { label: "What happens in a private online session", to: "/blog/what-happens-in-a-private-online-yoga-session" },
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
    ],
    faqs: [
      { q: "Is online yoga as safe as studio yoga?", a: "Live online yoga with camera on and a small class is safe for most healthy adults. Conditions needing physical support are better handled in person." },
      { q: "Does the teacher watch me the whole class?", a: "In a private session, yes. In live group classes the cap of eight students means everyone is seen and cued individually." },
      { q: "What if my internet drops?", a: "Tell us and we will arrange how to continue. Recordings of missed live group classes are available to members for 48 hours." },
    ],
    cta: PRIVATE_CTA,
  },
  {
    slug: "how-yog-jivan-matches-your-private-yoga-teacher",
    cat: "Private Yoga",
    cluster: "private",
    primaryKeyword: "private yoga teacher matching",
    title: "How Yog Jivan matches you with a private yoga teacher",
    seoTitle: "How We Match You With a Private Yoga Teacher",
    excerpt:
      "Matching is based on your level, your goals, your language and your schedule — not on who happens to be free. Here is exactly how the process runs.",
    metaDescription:
      "How Yog Jivan matches private 1-on-1 yoga students with a teacher: intake, level, focus, language, timezone, teacher continuity and what to do if it is not a fit.",
    read: "6 min",
    date: "2026-08-08",
    keyTakeaways: [
      "Matching uses level, focus, language and timezone — decided after the intake conversation.",
      "You keep the same teacher so progress is continuous.",
      "If the match is wrong, tell us and we will change it.",
    ],
    body: [
      { type: "p", text: "In private yoga the relationship does most of the work. A teacher who understands your history, your limits and your way of learning will get you further than a teacher who is simply available at 7pm. This is how we decide who teaches you." },
      { type: "h2", text: "Step one: the intake conversation" },
      { type: "p", text: "Before anything is scheduled, we spend around fifteen minutes on your background: previous practice, injuries or medical conditions, what you want from the sessions, how often you can realistically practise, and where you are in the world. Nothing about your health is used for advertising, and it is not shared beyond the teaching team." },
      { type: "h2", text: "Step two: what we match on" },
      { type: "ul", items: [
        "Level — complete beginner, returning after a break, steady practitioner, or advanced.",
        "Focus — general wellbeing, mobility, stress and sleep, desk-related tension, or therapeutic work agreed with your doctor.",
        "Language — we teach in English, Vietnamese and Hindi.",
        "Timezone and schedule — sessions need to sit at an hour you can actually keep.",
        "Teaching style — some students want a calm, methodical pace; others want to be pushed.",
      ]},
      { type: "h2", text: "Step three: your first session and a short review" },
      { type: "p", text: "The first session is also a practical test of the match. Afterwards we check in: was the pace right, were the explanations clear, did the timing work. Small adjustments are normal at this stage and are easier to make early." },
      { type: "h2", text: "Teacher continuity" },
      { type: "p", text: "You stay with the same teacher. That continuity is the point of private work — your teacher remembers which shoulder was painful last month and builds on the previous session instead of asking you to explain yourself again." },
      { type: "h2", text: "If the match is not right" },
      { type: "p", text: "Tell us. Preferring a different teacher, a different time or a different emphasis is a scheduling matter, not a complaint, and we would rather change it than have you quietly stop practising." },
    ],
    related: [
      { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      { label: "How to choose a private online yoga teacher", to: "/blog/how-to-choose-a-private-online-yoga-teacher" },
      { label: "About Yog Jivan", to: "/about" },
    ],
    faqs: [
      { q: "Can I request a specific teacher?", a: "Yes. Mention it in your enquiry and we will accommodate it where the schedule allows." },
      { q: "Which languages are available?", a: "English, Vietnamese and Hindi." },
      { q: "Will I always have the same teacher?", a: "Yes, that continuity is central to private work. Cover is arranged only if your teacher is unavailable and you agree to it." },
    ],
    cta: PRIVATE_CTA,
  },
  {
    slug: "private-online-yoga-for-beginners",
    cat: "Private Yoga",
    cluster: "private",
    primaryKeyword: "private online yoga for beginners",
    title: "Private online yoga for complete beginners: a calm way to start",
    seoTitle: "Private Online Yoga for Complete Beginners",
    excerpt:
      "If you are not flexible, not fit, or simply do not want to start in a room full of strangers, private 1-on-1 online yoga is a gentler entry point. Here is how it works.",
    metaDescription:
      "Starting yoga as a complete beginner with private 1-on-1 online sessions: what the first weeks look like, what you need, and honest expectations about progress.",
    read: "7 min",
    date: "2026-08-08",
    keyTakeaways: [
      "Flexibility is not a prerequisite — it is one possible outcome of practice.",
      "Private sessions let a beginner ask questions without holding a class up.",
      "Two or three short weekly sessions beat one long session you dread.",
    ],
    body: [
      { type: "p", text: "The most common reason people delay starting yoga is the fear of being the least capable person in the room. Private online sessions remove that room entirely: it is you, your teacher and an hour built around what you can currently do." },
      { type: "h2", text: "You do not need to be flexible" },
      { type: "p", text: "Flexibility is a possible result of practice, not a requirement for entry. A beginner private session is mostly about learning to stand, breathe and move with your spine supported — not about reaching your toes." },
      { type: "h2", text: "Why private suits nervous beginners" },
      { type: "ul", items: [
        "You can stop and ask what a word means without slowing anyone down.",
        "Postures are adapted to your body from the first minute rather than offered as an option.",
        "Your teacher can watch you the whole hour and catch habits before they set.",
        "Nobody else sees you learning.",
      ]},
      { type: "h2", text: "What the first few weeks usually look like" },
      { type: "p", text: "Early sessions focus on foundations: how to stand evenly, how to breathe without forcing, a handful of standing and seated postures, and how to rest properly at the end. Your teacher will typically give you one short thing to repeat between sessions. Expect some mild muscle awareness afterwards, and expect corrections — being corrected is the service you are paying for, not a sign of failure." },
      { type: "h2", text: "Honest expectations" },
      { type: "p", text: "Progress is uneven and personal. Some people feel calmer or sleep better early on; others notice physical change first; others take longer than they hoped. We will not promise a timeline. If you have a health condition, pregnancy, recent surgery or persistent pain, please speak to your doctor first — yoga supports wellbeing but is not medical treatment." },
      { type: "h2", text: "What you need to begin" },
      { type: "ul", items: [
        "A mat and a space about the size of the mat plus arm span.",
        "A phone, tablet or laptop placed side-on at hip height.",
        "Clothing you can bend in, and a cushion or folded blanket.",
        "A rough idea of two or three times each week you could realistically keep.",
      ]},
      { type: "h2", text: "Group classes are also an option" },
      { type: "p", text: "If cost or community matters more to you than individual attention, our live online group classes are capped at eight students and still include verbal correction. Many students start privately and move into group classes once they feel confident." },
    ],
    related: [
      { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      { label: "Yoga for Beginners", to: "/yoga-for-beginners" },
      { label: "What happens in a private online session", to: "/blog/what-happens-in-a-private-online-yoga-session" },
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
    ],
    faqs: [
      { q: "I am not flexible at all. Can I still start?", a: "Yes. Postures are adapted to your current range from the first session; flexibility is a result of practice, not a requirement." },
      { q: "How often should a beginner practise?", a: "Two or three manageable sessions a week are generally more useful than one long session you dread." },
      { q: "Is private more suitable than a group class for beginners?", a: "It depends on you. Private gives full attention and privacy; group classes give routine and community at a lower cost." },
    ],
    cta: PRIVATE_CTA,
  },
  {
    slug: "private-yoga-for-intermediate-and-advanced-students",
    cat: "Private Yoga",
    cluster: "private",
    primaryKeyword: "private yoga for intermediate and advanced students",
    title: "Private yoga for intermediate and advanced students: refining what you already have",
    seoTitle: "Private Yoga for Intermediate & Advanced Students",
    excerpt:
      "When a general class stops moving you forward, private work targets the specific pattern holding a posture back — and rebuilds the sequencing around your goal.",
    metaDescription:
      "How experienced practitioners use private 1-on-1 online yoga: refining alignment, working around plateaus and injuries, breath work and personalised sequencing.",
    read: "7 min",
    date: "2026-08-08",
    keyTakeaways: [
      "Plateaus are usually a pattern problem, not an effort problem.",
      "Private sessions let sequencing be built around one specific goal.",
      "Advanced work still starts from an honest assessment, not from the peak posture.",
    ],
    body: [
      { type: "p", text: "Experienced practitioners come to private sessions for a different reason than beginners. The question is rarely how to start; it is why one side always feels different, why a posture has not moved in a year, or how to keep practising around a shoulder that objects." },
      { type: "h2", text: "Plateaus are usually patterns" },
      { type: "p", text: "When a posture stops progressing, the limitation is often somewhere else entirely — a rib position, a hip that will not release, a breath pattern that tightens under load. In a group class those are hard to isolate. In an hour of individual attention they can be examined directly." },
      { type: "h2", text: "What private work typically covers at this level" },
      { type: "ul", items: [
        "Detailed alignment work in postures you already practise daily.",
        "Left-right asymmetry and where it originates.",
        "Safe, staged preparation for inversions, arm balances and deep backbends.",
        "Pranayama refinement and sustainable breath ratios.",
        "Practising intelligently around an injury, in coordination with your medical care.",
        "Building a home sequence that fits your week rather than an ideal week.",
      ]},
      { type: "h2", text: "Advanced does not mean unsupervised" },
      { type: "p", text: "Strong practitioners are the group most likely to injure themselves, usually by loading a familiar pattern harder. Private sessions start with an honest assessment of what is actually happening, not with the peak posture you want to photograph." },
      { type: "h2", text: "Teaching-adjacent work" },
      { type: "p", text: "Some experienced students want to deepen their understanding of sequencing, anatomy-informed cueing and the traditional basis of the practice. That can be built into private sessions. It is study support, not a certification programme — we do not issue teacher-training credentials through private sessions." },
      { type: "h2", text: "Combining private and group practice" },
      { type: "p", text: "A common pattern is one private session a week for refinement plus live group classes for rhythm and community. Our live online groups are capped at eight students and run for 60 minutes, so the group work still includes real correction." },
    ],
    related: [
      { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "Can an online teacher really correct your posture?", to: "/blog/can-an-online-yoga-teacher-correct-your-posture" },
    ],
    faqs: [
      { q: "Can private sessions help with a plateau?", a: "Usually, because a plateau is normally caused by a pattern elsewhere in the body that an hour of individual attention can isolate." },
      { q: "Can I practise privately while injured?", a: "Often yes, with medical clearance and clear communication about what your clinician has advised." },
      { q: "Do you offer teacher training?", a: "Private sessions can support study of sequencing and technique, but we do not issue teacher-training certification through them." },
    ],
    cta: PRIVATE_CTA,
  },
  {
    slug: "how-to-choose-a-private-online-yoga-teacher",
    cat: "Private Yoga",
    cluster: "private",
    primaryKeyword: "how to choose a private online yoga teacher",
    title: "How to choose a private online yoga teacher: questions worth asking",
    seoTitle: "How to Choose a Private Online Yoga Teacher",
    excerpt:
      "A practical checklist for judging an online private teacher — live versus recorded, class size, correction, health intake, continuity, language and how pricing is handled.",
    metaDescription:
      "What to ask before booking a private online yoga teacher: live teaching, correction method, health intake, teacher continuity, languages, scheduling and pricing clarity.",
    read: "7 min",
    date: "2026-08-08",
    keyTakeaways: [
      "Live and watched beats recorded and generic, whatever the library size.",
      "A teacher who asks about your health before the first session is a good sign.",
      "Vague answers about who teaches you and what it costs are a warning sign.",
    ],
    body: [
      { type: "p", text: "Booking a private teacher online means trusting someone you have not met with your body. These are the questions worth asking before you pay for anything — of us or of anyone else." },
      { type: "h2", text: "1. Is the session live, and will the teacher watch me?" },
      { type: "p", text: "A large recorded library is a different product from a live teacher. If nobody sees you practise, nobody can correct you. Ask directly whether the session is live and whether the camera must be on." },
      { type: "h2", text: "2. Do they ask about your health before teaching you?" },
      { type: "p", text: "A teacher who takes a booking without asking about injuries, surgery, pregnancy or medication is not being careful with you. Expect an intake conversation and expect to be told when something needs a doctor's clearance first." },
      { type: "h2", text: "3. Will you have the same teacher each time?" },
      { type: "p", text: "Rotating teachers means re-explaining your history repeatedly and losing the thread of your progress. Ask about continuity and about what happens if your teacher is unavailable." },
      { type: "h2", text: "4. How is correction actually delivered?" },
      { type: "ul", items: [
        "Ask how the camera should be placed — a teacher who cares will have a clear answer.",
        "Ask whether corrections are given by name during the session or only in a summary afterwards.",
        "Ask whether you can stop and ask questions mid-session.",
      ]},
      { type: "h2", text: "5. Language, timezone and scheduling" },
      { type: "p", text: "Precise instruction depends on shared language. Yog Jivan teaches in English, Vietnamese and Hindi, and schedules private sessions around your timezone. Check how rescheduling is handled before you need to reschedule." },
      { type: "h2", text: "6. Are claims and pricing handled honestly?" },
      { type: "ul", items: [
        "Be sceptical of promised cures, guaranteed timelines or dramatic percentage claims.",
        "Prefer verifiable proof — public reviews you can read yourself — over anonymous quotes.",
        "Expect a clear answer on cost, cancellation and what happens if you stop.",
      ]},
      { type: "h2", text: "How Yog Jivan answers these" },
      { type: "p", text: "Our private sessions are live, 60 minutes, camera on, with the same teacher each time, preceded by a short health and goals conversation, taught in English, Vietnamese or Hindi. Private scheduling and pricing are confirmed by enquiry because they depend on frequency and format, and our studio reviews are published on Google where you can read them yourself." },
    ],
    related: [
      { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      { label: "How we match you with a teacher", to: "/blog/how-yog-jivan-matches-your-private-yoga-teacher" },
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "About Yog Jivan", to: "/about" },
    ],
    faqs: [
      { q: "What is the most important question to ask?", a: "Whether the session is live and whether the teacher will actually watch and correct you. Everything else follows from that." },
      { q: "Is a cheaper recorded programme good enough?", a: "It can build a routine, but it cannot correct your alignment or adapt to an injury." },
      { q: "How do I know a teacher is trustworthy?", a: "Look for a health intake before teaching, verifiable public reviews, clear pricing and no promises of guaranteed medical outcomes." },
    ],
    cta: PRIVATE_CTA,
  },
];
