// Private 1-on-1 online yoga content cluster.
// Every post supports /private-online-yoga and links back to it contextually.
// No invented students, outcomes, timelines, prices, statistics or credentials.
// Editorial safety pass: no medical diagnosis or treatment claims, no comparative
// safety declarations, no unverified frequency/outcome guidance, no recording-policy
// assertions beyond the verified fact that private sessions are live.
import type { BlogPost } from "@/lib/blog/types";

const PRIVATE_CTA = {
  title: "Private 1-on-1 online yoga",
  sub: "Tell us your level, your goals and when you like to practise. Scheduling and pricing are arranged by enquiry.",
  primary: { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
  secondary: { label: "Live Online Group Classes", to: "/online-yoga-classes" },
};

const PUB_DATE = "2026-08-19";

export const PRIVATE_POSTS: BlogPost[] = [
  {
    slug: "what-happens-in-a-private-online-yoga-session",
    cat: "Private Yoga",
    cluster: "private",
    primaryKeyword: "what happens in a private online yoga session",
    title: "What Happens in a Private Online Yoga Session? A 60-Minute Walkthrough",
    seoTitle: "What Happens in a Private Online Yoga Session",
    excerpt:
      "An illustrative walkthrough of a private 1-on-1 online yoga session: the onboarding conversation, camera setup, the 60 minutes themselves and what follows.",
    metaDescription:
      "Walk through a private 1-on-1 online yoga session with Yog Jivan: onboarding conversation, camera and space setup, the live 60 minutes and what comes after.",
    read: "7 min",
    date: PUB_DATE,
    keyTakeaways: [
      "Private sessions run 60 minutes and are taught live on video.",
      "A short onboarding conversation happens before your first session.",
      "Camera on is required so your teacher can see and guide your alignment.",
    ],
    body: [
      { type: "p", text: "People often hesitate to book private online yoga because they cannot picture it. This is what a private 1-on-1 session with Yog Jivan generally involves, from the first conversation to the end of the hour. The exact shape of any session varies by student and by day." },
      { type: "h2", text: "Before your first session: a short conversation" },
      { type: "p", text: "We begin with a short onboarding conversation. It is not a sales call. Your teacher asks what you want from your practice, what you have done before and how much time you realistically have each week. If you have relevant health limitations, or advice from a clinician that should shape your practice, you can share it then so movements can be adapted. Yoga at Yog Jivan is a wellness practice and does not replace medical care." },
      { type: "h2", text: "Setting up your space and camera" },
      { type: "ul", items: [
        "Clear a space roughly the length of your mat plus arm span in each direction.",
        "Place the device side-on at about hip height, far enough back that your whole mat is in frame.",
        "Put the light in front of you rather than behind, so you are not a silhouette.",
        "Use headphones if the room echoes; hearing guidance clearly matters more than picture quality.",
      ]},
      { type: "p", text: "Camera on is required for private sessions. Without seeing you, a teacher can only narrate a class rather than guide one — which removes the reason for choosing private work. Your session is live and private; if you have questions about how anything is handled, ask us before you book." },
      { type: "h2", text: "The 60 minutes" },
      { type: "p", text: "An hour might open with settling and breath awareness, move through warming preparation, then into the main practice chosen for you — standing work, seated and floor work, or an individualised focus agreed with you. Your teacher watches continuously and gives verbal cues by name: which knee, which shoulder, which direction. The session usually closes with slowing-down work, a breathing practice and rest. This is illustrative rather than a fixed template; the sequence varies by student and by day." },
      { type: "h2", text: "How a private session differs from a group class" },
      { type: "ul", items: [
        "The sequence is chosen for your body and your goals, not for a room of eight people.",
        "You can stop and ask questions at any point.",
        "Postures are adapted for you rather than announced as options.",
        "Timing is arranged around your schedule and time zone.",
      ]},
      { type: "h2", text: "After the session" },
      { type: "p", text: "Your teacher will often suggest one or two things to practise between sessions — usually short and specific rather than a long home routine. Because you continue with the same teacher, the next session builds on the last one instead of starting over." },
      { type: "h2", text: "What we do not promise" },
      { type: "p", text: "We do not promise a fixed number of sessions to a fixed result, and we do not treat yoga as a substitute for medical care. What we can commit to is live attention, honest guidance and a practice that fits your situation." },
    ],
    related: [
      { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "Can an online teacher correct your posture?", to: "/blog/can-an-online-yoga-teacher-correct-your-posture" },
      { label: "Private online yoga for complete beginners", to: "/blog/private-online-yoga-for-beginners" },
    ],
    faqs: [
      { q: "How long is a private online yoga session?", a: "Sixty minutes, taught live. A short onboarding conversation before your first session is separate." },
      { q: "Do I have to keep my camera on?", a: "Yes. Private sessions depend on your teacher being able to see your alignment throughout the hour." },
      { q: "What equipment do I need?", a: "A mat and a stable device. A cushion, a belt or scarf, a chair and a couple of thick books cover most prop needs." },
      { q: "How much does a private session cost?", a: "Private scheduling and pricing are arranged by enquiry, because they depend on frequency and format." },
    ],
    cta: PRIVATE_CTA,
  },
  {
    slug: "can-an-online-yoga-teacher-correct-your-posture",
    cat: "Private Yoga",
    cluster: "private",
    primaryKeyword: "can an online yoga teacher correct your posture",
    title: "Can an Online Yoga Teacher Really Correct Your Posture? What They Can and Cannot See",
    seoTitle: "Can an Online Yoga Teacher Correct Your Posture?",
    excerpt:
      "A live teacher can observe a great deal of your movement when the camera is placed well — but an online view has real limits. Here is what it can and cannot show.",
    metaDescription:
      "What live online yoga guidance can and cannot see: camera placement, verbal cueing, the limits of a screen view, and when in-person or clinical support is appropriate.",
    read: "7 min",
    date: PUB_DATE,
    keyTakeaways: [
      "A live teacher can observe many visible aspects of your movement when the camera is placed well.",
      "An online view has limits and is not equivalent to in-person, hands-on assessment.",
      "Some situations are better served in person or with clinical support.",
    ],
    body: [
      { type: "p", text: "The honest answer is nuanced. A live teacher can observe many visible aspects of your movement and alignment when your camera is placed well and the class is small enough for individual attention. A pre-recorded video cannot observe anything at all. But a screen view is not equivalent to being in the room with someone, and it is not a substitute for hands-on or clinical assessment." },
      { type: "h2", text: "What a teacher can generally observe on screen" },
      { type: "ul", items: [
        "The broad shape of the spine — rounding, over-arching, and roughly where a bend is happening.",
        "Visible weight distribution through the feet and hands.",
        "Knee and elbow tracking relative to ankles and wrists.",
        "Shoulder position and visible neck or jaw tension.",
        "Breath rhythm, holding, and when a posture visibly stops being sustainable.",
      ]},
      { type: "h2", text: "What is harder or impossible to see" },
      { type: "p", text: "Subtle rotation, fine foot mechanics, load through a joint and anything you feel internally are difficult or impossible to read through a screen. That is why your teacher asks you questions during a private session rather than assuming, and why we ask you to speak up about discomfort rather than wait to be noticed." },
      { type: "h2", text: "Camera placement matters" },
      { type: "ul", items: [
        "A side-on view usually shows more about the shape of the spine than a front-on view.",
        "Hip height, roughly one and a half to two metres back, with the whole mat in frame.",
        "Light in front of you, not behind.",
        "Move the device for floor work if the frame cuts you off — your teacher will ask.",
      ]},
      { type: "h2", text: "How verbal guidance works" },
      { type: "p", text: "A hands-on adjustment moves you into a shape. A precise verbal cue asks you to find it yourself, which is what you are doing when you practise alone. Our live group classes are capped at eight students so there is time for named, individual cueing, and a private session gives you the whole hour." },
      { type: "h2", text: "When in-person or clinical support is more appropriate" },
      { type: "p", text: "If you need hands-on assistance, clinical rehabilitation or a medical assessment, please follow your clinician's advice — appropriate in-person or clinical support may serve you better than an online session. If that comes up in the onboarding conversation, we will say so rather than simply take a booking." },
    ],
    related: [
      { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      { label: "What happens in a private online session", to: "/blog/what-happens-in-a-private-online-yoga-session" },
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
    ],
    faqs: [
      { q: "Is online guidance the same as in-person teaching?", a: "No. A live teacher can observe a lot on screen, but an online view has limits and cannot replace hands-on or clinical assessment." },
      { q: "Does the teacher watch me the whole class?", a: "In a private session, yes. In live group classes the cap of eight students means there is time to see and cue students individually." },
      { q: "What if my internet drops?", a: "Tell us and we will arrange how to continue. Recordings of missed live group classes are available to members for 48 hours." },
    ],
    cta: PRIVATE_CTA,
  },
  {
    slug: "how-yog-jivan-matches-your-private-yoga-teacher",
    cat: "Private Yoga",
    cluster: "private",
    primaryKeyword: "private yoga teacher matching",
    title: "How Yog Jivan Matches You With a Private Yoga Teacher — and Why Continuity Matters",
    seoTitle: "How We Match You With a Private Yoga Teacher",
    excerpt:
      "Matching considers your level, your goals, your language preference and your schedule. Here is how the process runs and what happens if the match is not right.",
    metaDescription:
      "How Yog Jivan matches private 1-on-1 yoga students with a teacher: onboarding, level, focus, language availability, time zone, continuity and changing your match.",
    read: "6 min",
    date: PUB_DATE,
    keyTakeaways: [
      "Matching considers level, focus, language preference and time zone.",
      "Sessions are generally kept with the same matched teacher for continuity.",
      "If the match is not right, tell us and we will arrange a change.",
    ],
    body: [
      { type: "p", text: "In private yoga, working with a teacher who knows your history, your limits and your way of learning is one of the main reasons students choose the format. This is how we decide who teaches you." },
      { type: "h2", text: "Step one: the onboarding conversation" },
      { type: "p", text: "Before anything is scheduled, we spend a short conversation on your background: previous practice, any relevant health limitations or clinician advice, what you want from the sessions, how often you can realistically practise, and where you are in the world. Information you share is handled in line with our privacy policy and is not used for advertising." },
      { type: "h2", text: "Step two: what we consider" },
      { type: "ul", items: [
        "Level — complete beginner, returning after a break, steady practitioner, or advanced.",
        "Focus — general wellbeing, mobility, stress and sleep, or desk-related tension.",
        "Language — Yog Jivan offers teaching across English, Vietnamese and Hindi, subject to teacher availability.",
        "Time zone and schedule — sessions need to sit at an hour you can actually keep.",
        "Teaching style — some students want a calm, methodical pace; others want to be pushed.",
      ]},
      { type: "h2", text: "Step three: your first session and a short review" },
      { type: "p", text: "The first session is also a practical test of the match. Afterwards we check in: was the pace right, were the explanations clear, did the timing work. Small adjustments are normal at this stage and are easier to make early." },
      { type: "h2", text: "Why continuity matters" },
      { type: "p", text: "Sessions are generally kept with the same matched teacher for continuity. That continuity is much of the point of private work — your teacher remembers what you were working on last month and builds on the previous session instead of asking you to explain yourself again." },
      { type: "h2", text: "If the match is not right" },
      { type: "p", text: "Tell us. Preferring a different teacher, a different time or a different emphasis is a scheduling matter, not a complaint, and we would rather change it than have you quietly stop practising." },
    ],
    related: [
      { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      { label: "How to choose a private online yoga teacher", to: "/blog/how-to-choose-a-private-online-yoga-teacher" },
      { label: "About Yog Jivan", to: "/about" },
    ],
    faqs: [
      { q: "Can I request a specific teacher?", a: "Yes. Mention it in your enquiry and we will accommodate it where availability allows." },
      { q: "Which languages are available?", a: "Yog Jivan offers matching across English, Vietnamese and Hindi, subject to teacher availability. Tell us your preference in your enquiry." },
      { q: "Will I have the same teacher each session?", a: "Sessions are generally kept with the same matched teacher for continuity, unless you and the team agree to a change or availability requires an agreed adjustment." },
    ],
    cta: PRIVATE_CTA,
  },
  {
    slug: "private-online-yoga-for-beginners",
    cat: "Private Yoga",
    cluster: "private",
    primaryKeyword: "private online yoga for beginners",
    title: "Private Online Yoga for Complete Beginners: What to Expect Before Session One",
    seoTitle: "Private Online Yoga for Complete Beginners",
    excerpt:
      "If you are not flexible, not fit, or simply do not want to start in a room full of strangers, private 1-on-1 online yoga is a quiet way to begin. Here is how it works.",
    metaDescription:
      "Starting yoga as a complete beginner with private 1-on-1 online sessions: what the first sessions cover, what you need, and honest expectations about progress.",
    read: "7 min",
    date: PUB_DATE,
    keyTakeaways: [
      "Flexibility is not a prerequisite — it is one possible outcome of practice.",
      "Private sessions let a beginner ask questions without holding a class up.",
      "Choose a frequency you can realistically sustain and discuss it with your teacher.",
    ],
    body: [
      { type: "p", text: "Some people put off starting yoga because they do not want to be the least experienced person in the room. Private online sessions remove that room entirely: it is you, your teacher and an hour built around what you can currently do." },
      { type: "h2", text: "You do not need to be flexible" },
      { type: "p", text: "Flexibility is a possible result of practice, not a requirement for entry. A beginner private session is mostly about learning to stand, breathe and move with your spine supported — not about reaching your toes." },
      { type: "h2", text: "Why private suits nervous beginners" },
      { type: "ul", items: [
        "You can stop and ask what a word means without slowing anyone down.",
        "Postures are adapted to your body from the first minute rather than offered as an option.",
        "Your teacher can watch you for the whole hour rather than sharing attention with a group.",
        "Nobody else sees you learning.",
      ]},
      { type: "h2", text: "What early sessions tend to cover" },
      { type: "p", text: "Early sessions usually focus on foundations: how to stand evenly, how to breathe without forcing, a handful of standing and seated postures, and how to rest properly at the end. Your teacher will often give you one short thing to repeat between sessions. Being corrected is the service you are paying for, not a sign of failure." },
      { type: "h2", text: "Honest expectations" },
      { type: "p", text: "People progress differently, and no fixed result or timeline is promised. If you have a health condition, are pregnant, have had recent surgery or live with persistent pain, please speak to your clinician first and share any relevant limitations or advice with your teacher — yoga supports wellbeing but is not medical treatment." },
      { type: "h2", text: "What you need to begin" },
      { type: "ul", items: [
        "A mat and a space about the size of the mat plus arm span.",
        "A phone, tablet or laptop placed side-on at hip height.",
        "Clothing you can bend in, and a cushion or folded blanket.",
        "A realistic idea of when in your week you could practise.",
      ]},
      { type: "h2", text: "Group classes are also an option" },
      { type: "p", text: "If cost or community matters more to you than individual attention, our live online group classes are capped at eight students and still include verbal guidance. Private and group formats can also be combined — tell us what you are looking for and we will explain the options." },
    ],
    related: [
      { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      { label: "Yoga for Beginners", to: "/yoga-for-beginners" },
      { label: "What happens in a private online session", to: "/blog/what-happens-in-a-private-online-yoga-session" },
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
    ],
    faqs: [
      { q: "I am not flexible at all. Can I still start?", a: "Yes. Postures are adapted to your current range from the first session; flexibility is a result of practice, not a requirement." },
      { q: "How often should a beginner practise?", a: "Choose a frequency you can realistically sustain, and discuss it with your teacher so your sessions and home practice fit your week." },
      { q: "Is private more suitable than a group class for beginners?", a: "It depends on you. Private gives full attention and privacy; group classes give routine and community at a lower cost." },
    ],
    cta: PRIVATE_CTA,
  },
  {
    slug: "private-yoga-for-intermediate-and-advanced-students",
    cat: "Private Yoga",
    cluster: "private",
    primaryKeyword: "private yoga for intermediate and advanced students",
    title: "Private Yoga for Intermediate & Advanced Students: Alignment, Plateaus and Advanced Progression",
    seoTitle: "Private Yoga for Intermediate & Advanced Students",
    excerpt:
      "When a general class stops feeling useful, private work gives time to examine technique, breath and transitions in the postures you already practise.",
    metaDescription:
      "How experienced practitioners use private 1-on-1 online yoga: refining alignment, examining plateaus, staged progression, breath work and personalised sequencing.",
    read: "7 min",
    date: PUB_DATE,
    keyTakeaways: [
      "Private sessions give time to examine technique, mobility, strength, breath and transitions.",
      "Sequencing can be built around one specific goal.",
      "Advanced work starts from your current ability, with no promised pose or timeline.",
    ],
    body: [
      { type: "p", text: "Experienced practitioners come to private sessions for different reasons than beginners. The question is rarely how to start; it is why one side feels different, why a posture has not moved in a while, or how to keep practising thoughtfully around a shoulder that objects." },
      { type: "h2", text: "Working on a plateau" },
      { type: "p", text: "When a posture stops progressing, there is rarely a single explanation. A private session gives time to examine technique, mobility, strength, breath and transitions that may be contributing — the kind of unhurried look that is hard to fit into a group class." },
      { type: "h2", text: "What private work often covers at this level" },
      { type: "ul", items: [
        "Detailed alignment work in postures you already practise regularly.",
        "Observing left-right asymmetry and exploring technique around it.",
        "Staged preparation for inversions, arm balances and deeper backbends, according to your current ability.",
        "Pranayama refinement and sustainable breath ratios.",
        "Practising thoughtfully around an injury, in line with your clinician's advice.",
        "Building a home sequence that fits your actual week.",
      ]},
      { type: "h2", text: "Advanced does not mean unsupervised" },
      { type: "p", text: "Experienced practice benefits from an outside eye. Private sessions start from an honest look at what is happening now, not from the peak posture you want to photograph. We do not promise specific poses or fixed timelines." },
      { type: "h2", text: "Teaching-adjacent work" },
      { type: "p", text: "Some experienced students want to deepen their understanding of sequencing, anatomy-informed cueing and the traditional basis of the practice. That can be built into private sessions. It is study support, not a certification programme — we do not issue teacher-training credentials through private sessions." },
      { type: "h2", text: "Combining private and group practice" },
      { type: "p", text: "Some students combine private sessions for refinement with live group classes for rhythm and community. It is one optional format among others. Our live online groups are capped at eight students and run for 60 minutes, so group work still includes individual verbal guidance." },
    ],
    related: [
      { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "Can an online teacher correct your posture?", to: "/blog/can-an-online-yoga-teacher-correct-your-posture" },
    ],
    faqs: [
      { q: "Can private sessions help when progress has stalled?", a: "They give time to examine technique, mobility, strength, breath and transitions in detail, which is difficult in a group setting." },
      { q: "Can I practise privately while injured?", a: "Follow your clinician's advice first, then share any relevant limitations with your teacher so the session can be adapted." },
      { q: "Do you offer teacher training?", a: "Private sessions can support study of sequencing and technique, but we do not issue teacher-training certification through them." },
    ],
    cta: PRIVATE_CTA,
  },
  {
    slug: "how-to-choose-a-private-online-yoga-teacher",
    cat: "Private Yoga",
    cluster: "private",
    primaryKeyword: "how to choose a private online yoga teacher",
    title: "How to Choose a Private Online Yoga Teacher: 9 Things to Check Before You Book",
    seoTitle: "How to Choose a Private Online Yoga Teacher",
    excerpt:
      "A neutral checklist for judging any private online yoga teacher — live teaching, experience, safety, feedback, continuity, language, privacy, scheduling and pricing.",
    metaDescription:
      "Nine things to check before booking a private online yoga teacher: live teaching, verifiable experience, safety and scope, feedback, continuity, language, privacy, scheduling and pricing.",
    read: "8 min",
    date: PUB_DATE,
    keyTakeaways: [
      "Live and observed is a different product from a recorded library.",
      "Clear answers on continuity, privacy and pricing are a good sign.",
      "These checks apply to any teacher, not only to Yog Jivan.",
    ],
    body: [
      { type: "p", text: "Booking a private teacher online means working closely with someone you have not met in person. These nine checks are worth applying before you pay for anything — with us or with anyone else." },
      { type: "h2", text: "1. Is the session live and interactive?" },
      { type: "p", text: "A large recorded library is a different product from a live teacher. If nobody is watching while you practise, nobody can respond to what you are doing. Ask directly whether the session is live, whether the camera must be on, and whether you can ask questions during the hour." },
      { type: "h2", text: "2. What relevant teaching experience can be verified?" },
      { type: "p", text: "Ask how long the teacher has taught, what they mainly teach, and whether there is anything you can check independently — a public profile, published reviews, a school or studio they teach with. Prefer verifiable information over anonymous quotes." },
      { type: "h2", text: "3. How does the teacher handle safety and scope of practice?" },
      { type: "p", text: "A careful teacher will invite you to share relevant health limitations or clinician advice before you practise, will adapt movements accordingly, and will be clear that yoga is not medical treatment. Ask how they respond if something hurts and whether they will refer you back to a clinician when appropriate." },
      { type: "h2", text: "4. How is camera-based feedback delivered?" },
      { type: "ul", items: [
        "Ask how the camera should be placed — a teacher who cares will have a clear answer.",
        "Ask whether guidance is given by name during the session or only summarised afterwards.",
        "Ask what they can and cannot see on screen, and how they check in with you.",
      ]},
      { type: "h2", text: "5. Will you have teacher continuity?" },
      { type: "p", text: "Rotating teachers means re-explaining your background repeatedly. Ask whether the same teacher continues with you by default, and what happens when they are unavailable." },
      { type: "h2", text: "6. Can they teach in a language you understand clearly?" },
      { type: "p", text: "Precise instruction depends on shared language, especially for anatomy and direction cues. Ask which languages a teacher can teach in comfortably, rather than assuming a school-wide list applies to every individual teacher." },
      { type: "h2", text: "7. How are privacy and recordings handled?" },
      { type: "p", text: "Ask what happens to anything you share, whether sessions are recorded in any circumstance, and where their privacy policy is published. You should be able to get a straight answer before you book." },
      { type: "h2", text: "8. How do scheduling, rescheduling and time zones work?" },
      { type: "p", text: "Check how sessions are booked, how far ahead, how rescheduling works and what happens if you miss one — before you need to reschedule. Confirm the time zone in writing." },
      { type: "h2", text: "9. Is pricing and what is included explained clearly before payment?" },
      { type: "ul", items: [
        "Ask exactly what a session includes and what costs extra.",
        "Ask about cancellation and what happens if you stop.",
        "Be sceptical of promised cures, guaranteed timelines or dramatic percentage claims from anyone.",
      ]},
      { type: "h2", text: "How Yog Jivan approaches these points" },
      { type: "p", text: "For transparency, here are our own answers. Private sessions are live, 60 minutes, camera on, with a dedicated teacher who continues with you by default, preceded by a short onboarding conversation. Yog Jivan offers matching across English, Vietnamese and Hindi subject to teacher availability. Private scheduling and pricing are confirmed by enquiry because they depend on frequency and format, and our studio reviews are published on Google where you can read them yourself. Apply the same nine checks to anyone else you are considering." },
    ],
    related: [
      { label: "Private 1-on-1 Online Yoga", to: "/private-online-yoga" },
      { label: "How we match you with a teacher", to: "/blog/how-yog-jivan-matches-your-private-yoga-teacher" },
      { label: "Live Online Yoga Classes", to: "/online-yoga-classes" },
      { label: "About Yog Jivan", to: "/about" },
    ],
    faqs: [
      { q: "What is the most important question to ask?", a: "Whether the session is live and whether the teacher will actually observe and respond to you. Several of the other checks follow from that." },
      { q: "Is a cheaper recorded programme good enough?", a: "It can help you build a routine, but it cannot observe you live or personalise cues in real time." },
      { q: "How do I know a teacher is trustworthy?", a: "Look for a safety-aware conversation before teaching, verifiable public information, clear pricing and no promises of guaranteed medical outcomes." },
    ],
    cta: PRIVATE_CTA,
  },
];
