/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookOnlineYogaRouteImport } from './routes/book-online-yoga'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as OnlinePrivateYogaRouteImport } from './routes/online-private-yoga'
import { Route as OnlineYogaClassesRouteImport } from './routes/online-yoga-classes'
import { Route as PeriodSafeYogaRouteImport } from './routes/period-safe-yoga'
import { Route as PersonalTrainingRouteImport } from './routes/personal-training'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivateOnlineYogaRouteImport } from './routes/private-online-yoga'
import { Route as PrivateYogaRouteImport } from './routes/private-yoga'
import { Route as PrivateYogaClassesRouteImport } from './routes/private-yoga-classes'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as YogaForBackPainRouteImport } from './routes/yoga-for-back-pain'
import { Route as YogaForBeginnersRouteImport } from './routes/yoga-for-beginners'
import { Route as YogaForExpatsInVietnamRouteImport } from './routes/yoga-for-expats-in-vietnam'
import { Route as YogaForPcodRouteImport } from './routes/yoga-for-pcod'
import { Route as YogaForStressRouteImport } from './routes/yoga-for-stress'
import { Route as YogaForThyroidRouteImport } from './routes/yoga-for-thyroid'
import { Route as YogaForWeightLossRouteImport } from './routes/yoga-for-weight-loss'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookOnlineYogaRoute = BookOnlineYogaRouteImport.update({
  id: '/book-online-yoga',
  path: '/book-online-yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlinePrivateYogaRoute = OnlinePrivateYogaRouteImport.update({
  id: '/online-private-yoga',
  path: '/online-private-yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineYogaClassesRoute = OnlineYogaClassesRouteImport.update({
  id: '/online-yoga-classes',
  path: '/online-yoga-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodSafeYogaRoute = PeriodSafeYogaRouteImport.update({
  id: '/period-safe-yoga',
  path: '/period-safe-yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalTrainingRoute = PersonalTrainingRouteImport.update({
  id: '/personal-training',
  path: '/personal-training',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateOnlineYogaRoute = PrivateOnlineYogaRouteImport.update({
  id: '/private-online-yoga',
  path: '/private-online-yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateYogaRoute = PrivateYogaRouteImport.update({
  id: '/private-yoga',
  path: '/private-yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateYogaClassesRoute = PrivateYogaClassesRouteImport.update({
  id: '/private-yoga-classes',
  path: '/private-yoga-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaForBackPainRoute = YogaForBackPainRouteImport.update({
  id: '/yoga-for-back-pain',
  path: '/yoga-for-back-pain',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaForBeginnersRoute = YogaForBeginnersRouteImport.update({
  id: '/yoga-for-beginners',
  path: '/yoga-for-beginners',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaForExpatsInVietnamRoute = YogaForExpatsInVietnamRouteImport.update({
  id: '/yoga-for-expats-in-vietnam',
  path: '/yoga-for-expats-in-vietnam',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaForPcodRoute = YogaForPcodRouteImport.update({
  id: '/yoga-for-pcod',
  path: '/yoga-for-pcod',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaForStressRoute = YogaForStressRouteImport.update({
  id: '/yoga-for-stress',
  path: '/yoga-for-stress',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaForThyroidRoute = YogaForThyroidRouteImport.update({
  id: '/yoga-for-thyroid',
  path: '/yoga-for-thyroid',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaForWeightLossRoute = YogaForWeightLossRouteImport.update({
  id: '/yoga-for-weight-loss',
  path: '/yoga-for-weight-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book-online-yoga': typeof BookOnlineYogaRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/gallery': typeof GalleryRoute
  '/mcp': typeof McpRoute
  '/online': typeof OnlineRoute
  '/online-private-yoga': typeof OnlinePrivateYogaRoute
  '/online-yoga-classes': typeof OnlineYogaClassesRoute
  '/period-safe-yoga': typeof PeriodSafeYogaRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/privacy': typeof PrivacyRoute
  '/private-online-yoga': typeof PrivateOnlineYogaRoute
  '/private-yoga': typeof PrivateYogaRoute
  '/private-yoga-classes': typeof PrivateYogaClassesRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/yoga-for-back-pain': typeof YogaForBackPainRoute
  '/yoga-for-beginners': typeof YogaForBeginnersRoute
  '/yoga-for-expats-in-vietnam': typeof YogaForExpatsInVietnamRoute
  '/yoga-for-pcod': typeof YogaForPcodRoute
  '/yoga-for-stress': typeof YogaForStressRoute
  '/yoga-for-thyroid': typeof YogaForThyroidRoute
  '/yoga-for-weight-loss': typeof YogaForWeightLossRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book-online-yoga': typeof BookOnlineYogaRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/gallery': typeof GalleryRoute
  '/mcp': typeof McpRoute
  '/online': typeof OnlineRoute
  '/online-private-yoga': typeof OnlinePrivateYogaRoute
  '/online-yoga-classes': typeof OnlineYogaClassesRoute
  '/period-safe-yoga': typeof PeriodSafeYogaRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/privacy': typeof PrivacyRoute
  '/private-online-yoga': typeof PrivateOnlineYogaRoute
  '/private-yoga': typeof PrivateYogaRoute
  '/private-yoga-classes': typeof PrivateYogaClassesRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/yoga-for-back-pain': typeof YogaForBackPainRoute
  '/yoga-for-beginners': typeof YogaForBeginnersRoute
  '/yoga-for-expats-in-vietnam': typeof YogaForExpatsInVietnamRoute
  '/yoga-for-pcod': typeof YogaForPcodRoute
  '/yoga-for-stress': typeof YogaForStressRoute
  '/yoga-for-thyroid': typeof YogaForThyroidRoute
  '/yoga-for-weight-loss': typeof YogaForWeightLossRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book-online-yoga': typeof BookOnlineYogaRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/gallery': typeof GalleryRoute
  '/mcp': typeof McpRoute
  '/online': typeof OnlineRoute
  '/online-private-yoga': typeof OnlinePrivateYogaRoute
  '/online-yoga-classes': typeof OnlineYogaClassesRoute
  '/period-safe-yoga': typeof PeriodSafeYogaRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/privacy': typeof PrivacyRoute
  '/private-online-yoga': typeof PrivateOnlineYogaRoute
  '/private-yoga': typeof PrivateYogaRoute
  '/private-yoga-classes': typeof PrivateYogaClassesRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/yoga-for-back-pain': typeof YogaForBackPainRoute
  '/yoga-for-beginners': typeof YogaForBeginnersRoute
  '/yoga-for-expats-in-vietnam': typeof YogaForExpatsInVietnamRoute
  '/yoga-for-pcod': typeof YogaForPcodRoute
  '/yoga-for-stress': typeof YogaForStressRoute
  '/yoga-for-thyroid': typeof YogaForThyroidRoute
  '/yoga-for-weight-loss': typeof YogaForWeightLossRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/book-online-yoga'
    | '/contact'
    | '/corporate'
    | '/gallery'
    | '/mcp'
    | '/online'
    | '/online-private-yoga'
    | '/online-yoga-classes'
    | '/period-safe-yoga'
    | '/personal-training'
    | '/privacy'
    | '/private-online-yoga'
    | '/private-yoga'
    | '/private-yoga-classes'
    | '/programs'
    | '/sitemap.xml'
    | '/testimonials'
    | '/yoga-for-back-pain'
    | '/yoga-for-beginners'
    | '/yoga-for-expats-in-vietnam'
    | '/yoga-for-pcod'
    | '/yoga-for-stress'
    | '/yoga-for-thyroid'
    | '/yoga-for-weight-loss'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/blog/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/book-online-yoga'
    | '/contact'
    | '/corporate'
    | '/gallery'
    | '/mcp'
    | '/online'
    | '/online-private-yoga'
    | '/online-yoga-classes'
    | '/period-safe-yoga'
    | '/personal-training'
    | '/privacy'
    | '/private-online-yoga'
    | '/private-yoga'
    | '/private-yoga-classes'
    | '/programs'
    | '/sitemap.xml'
    | '/testimonials'
    | '/yoga-for-back-pain'
    | '/yoga-for-beginners'
    | '/yoga-for-expats-in-vietnam'
    | '/yoga-for-pcod'
    | '/yoga-for-stress'
    | '/yoga-for-thyroid'
    | '/yoga-for-weight-loss'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/blog'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/book-online-yoga'
    | '/contact'
    | '/corporate'
    | '/gallery'
    | '/mcp'
    | '/online'
    | '/online-private-yoga'
    | '/online-yoga-classes'
    | '/period-safe-yoga'
    | '/personal-training'
    | '/privacy'
    | '/private-online-yoga'
    | '/private-yoga'
    | '/private-yoga-classes'
    | '/programs'
    | '/sitemap.xml'
    | '/testimonials'
    | '/yoga-for-back-pain'
    | '/yoga-for-beginners'
    | '/yoga-for-expats-in-vietnam'
    | '/yoga-for-pcod'
    | '/yoga-for-stress'
    | '/yoga-for-thyroid'
    | '/yoga-for-weight-loss'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/blog/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookOnlineYogaRoute: typeof BookOnlineYogaRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  GalleryRoute: typeof GalleryRoute
  McpRoute: typeof McpRoute
  OnlineRoute: typeof OnlineRoute
  OnlinePrivateYogaRoute: typeof OnlinePrivateYogaRoute
  OnlineYogaClassesRoute: typeof OnlineYogaClassesRoute
  PeriodSafeYogaRoute: typeof PeriodSafeYogaRoute
  PersonalTrainingRoute: typeof PersonalTrainingRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivateOnlineYogaRoute: typeof PrivateOnlineYogaRoute
  PrivateYogaRoute: typeof PrivateYogaRoute
  PrivateYogaClassesRoute: typeof PrivateYogaClassesRoute
  ProgramsRoute: typeof ProgramsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
  YogaForBackPainRoute: typeof YogaForBackPainRoute
  YogaForBeginnersRoute: typeof YogaForBeginnersRoute
  YogaForExpatsInVietnamRoute: typeof YogaForExpatsInVietnamRoute
  YogaForPcodRoute: typeof YogaForPcodRoute
  YogaForStressRoute: typeof YogaForStressRoute
  YogaForThyroidRoute: typeof YogaForThyroidRoute
  YogaForWeightLossRoute: typeof YogaForWeightLossRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-online-yoga': {
      id: '/book-online-yoga'
      path: '/book-online-yoga'
      fullPath: '/book-online-yoga'
      preLoaderRoute: typeof BookOnlineYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-private-yoga': {
      id: '/online-private-yoga'
      path: '/online-private-yoga'
      fullPath: '/online-private-yoga'
      preLoaderRoute: typeof OnlinePrivateYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-yoga-classes': {
      id: '/online-yoga-classes'
      path: '/online-yoga-classes'
      fullPath: '/online-yoga-classes'
      preLoaderRoute: typeof OnlineYogaClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/period-safe-yoga': {
      id: '/period-safe-yoga'
      path: '/period-safe-yoga'
      fullPath: '/period-safe-yoga'
      preLoaderRoute: typeof PeriodSafeYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-training': {
      id: '/personal-training'
      path: '/personal-training'
      fullPath: '/personal-training'
      preLoaderRoute: typeof PersonalTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-online-yoga': {
      id: '/private-online-yoga'
      path: '/private-online-yoga'
      fullPath: '/private-online-yoga'
      preLoaderRoute: typeof PrivateOnlineYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-yoga': {
      id: '/private-yoga'
      path: '/private-yoga'
      fullPath: '/private-yoga'
      preLoaderRoute: typeof PrivateYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-yoga-classes': {
      id: '/private-yoga-classes'
      path: '/private-yoga-classes'
      fullPath: '/private-yoga-classes'
      preLoaderRoute: typeof PrivateYogaClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga-for-back-pain': {
      id: '/yoga-for-back-pain'
      path: '/yoga-for-back-pain'
      fullPath: '/yoga-for-back-pain'
      preLoaderRoute: typeof YogaForBackPainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga-for-beginners': {
      id: '/yoga-for-beginners'
      path: '/yoga-for-beginners'
      fullPath: '/yoga-for-beginners'
      preLoaderRoute: typeof YogaForBeginnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga-for-expats-in-vietnam': {
      id: '/yoga-for-expats-in-vietnam'
      path: '/yoga-for-expats-in-vietnam'
      fullPath: '/yoga-for-expats-in-vietnam'
      preLoaderRoute: typeof YogaForExpatsInVietnamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga-for-pcod': {
      id: '/yoga-for-pcod'
      path: '/yoga-for-pcod'
      fullPath: '/yoga-for-pcod'
      preLoaderRoute: typeof YogaForPcodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga-for-stress': {
      id: '/yoga-for-stress'
      path: '/yoga-for-stress'
      fullPath: '/yoga-for-stress'
      preLoaderRoute: typeof YogaForStressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga-for-thyroid': {
      id: '/yoga-for-thyroid'
      path: '/yoga-for-thyroid'
      fullPath: '/yoga-for-thyroid'
      preLoaderRoute: typeof YogaForThyroidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga-for-weight-loss': {
      id: '/yoga-for-weight-loss'
      path: '/yoga-for-weight-loss'
      fullPath: '/yoga-for-weight-loss'
      preLoaderRoute: typeof YogaForWeightLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookOnlineYogaRoute: BookOnlineYogaRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  GalleryRoute: GalleryRoute,
  McpRoute: McpRoute,
  OnlineRoute: OnlineRoute,
  OnlinePrivateYogaRoute: OnlinePrivateYogaRoute,
  OnlineYogaClassesRoute: OnlineYogaClassesRoute,
  PeriodSafeYogaRoute: PeriodSafeYogaRoute,
  PersonalTrainingRoute: PersonalTrainingRoute,
  PrivacyRoute: PrivacyRoute,
  PrivateOnlineYogaRoute: PrivateOnlineYogaRoute,
  PrivateYogaRoute: PrivateYogaRoute,
  PrivateYogaClassesRoute: PrivateYogaClassesRoute,
  ProgramsRoute: ProgramsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
  YogaForBackPainRoute: YogaForBackPainRoute,
  YogaForBeginnersRoute: YogaForBeginnersRoute,
  YogaForExpatsInVietnamRoute: YogaForExpatsInVietnamRoute,
  YogaForPcodRoute: YogaForPcodRoute,
  YogaForStressRoute: YogaForStressRoute,
  YogaForThyroidRoute: YogaForThyroidRoute,
  YogaForWeightLossRoute: YogaForWeightLossRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
